### ISSUE TITLE
incorrect timestamp in Transaction details

### ISSUE THREAD

**Issue by eyalfishler** [moneroexamples/openmonero#112]
incorrect timestamp showing in Transaction details
(unless your a [Neanderthals](https://en.wikipedia.org/wiki/Timeline_of_human_prehistory) )

![screenshot 2018-11-06 13 54 55](https://user-images.githubusercontent.com/282129/48096345-cb497600-e1cb-11e8-8bd3-e8db16341478.png)

**Comment by moneroexamples** [comment]
Thanks again. Should be fixed in https://github.com/moneroexamples/openmonero/commit/53fa5671a3682cbc159be4f95f352a1de31be634  

(probably you will need to hard refresh your browser to see any changes, so that the browser does not load cashed files)

**Comment by eyalfishler** [comment]
Fixed. Thanks for the VERY fast response and the great project.
![screenshot 2018-11-06 16 13 53](https://user-images.githubusercontent.com/282129/48102250-0c975100-e1df-11e8-97cc-a890911d66d0.png)

**Comment by moneroexamples** [comment]
Don't have anything special. Usually I get contacted through github issues, reddit or email. I could also go to, e.g., https://mattermost.getmonero.org, for more interactive communication.
