### ISSUE TITLE
Fork question

### ISSUE THREAD

**Issue by RomyToklio** [moneroexamples/openmonero#114]
Hi, is the web wallet sending functionality  working on new monero fork ? 
Thank you

**Comment by moneroexamples** [comment]
Yes, it should. You can always run the wallet and backend on testnet or stagenet networks to test it. For instance, my stagenet version is here http://139.162.60.17:81 . You can login using default seed and try making some stagenet transactions.

But openmonero  is still very much in development stage, so bugs and some issues are obviously possible.

**Comment by moneroexamples** [comment]
Closing as there seem to be no more future questions.
