### ISSUE TITLE
 HTTP_CLIENT: Failed to SEND

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/openmonero#118]
https://github.com/moneroexamples/openmonero/commit/cf4857268125cf32f55c8aea3281574755ea91e6#commitcomment-31867621

Hi @moneroexamples i;m encountering a issue, and i was wondering if you get it to, is this;

2019-01-08 09:17:55.522 7f07b53e8c40 ERROR net.http contrib/epee/include/net/http_client.h:397 HTTP_CLIENT: Failed to SEND 2019-01-08 09:17:55.522 7f07b53e8c40 INFO net.http contrib/epee/include/storages/http_abstract_invoke.h:53 Failed to invoke http request to /sendrawtransaction Error sending tx: 2019-01-08 09:17:55,522 ERROR [openmonero] rpc->commit_tx() commit_tx failed 2019-01-08 09:17:55,522 ERROR [openmonero] "Reason not given by daemon. A guess is 'Failed to check ringct signatures!'."
HTTP_CLIENT loses the connection for some reason, after i hit send again right away it works well tho, do you have the same problem? Thanks

Kind Regards
@moneroexamples
Owner
moneroexamples replied 5 minutes ago •

    after i hit send again right away it works well tho, do you have the same problem?

I encountered this issue. I don't know what causes it atm as it does not happen often.

Looking into is something on my "todo list", but haven't had time yet to look into it thoroughly. If you will have more info on it, when it happens, how to replicate it, etc, please make regular issue with the info. I would be grateful for any info.
@italocoin-project
italocoin-project replied 39 seconds from now

It happens pretty often, and my guess is that the HTTP_CLIENT gets timed out, and when you send it connects again, my guess that this commit could cause the problem; https://github.com/monero-project/monero/pull/3962/commits/55c7fb87a99cbd89fe2d98de7bde9854ee12b161

to replicate it its enought to wait a bit on the page, i think we should add a http_client request like a ping to maintain the connection on, let me know what do you think about it, thanks

Regards

**Comment by moneroexamples** [comment]
Just for the record that I also experience this issue:

```
2019-01-09 06:28:07.736     7f9b73036c00        ERROR   net.http        contrib/epee/include/net/http_client.h:397    HTTP_CLIENT: Failed to SEND
2019-01-09 06:28:07.736     7f9b73036c00        INFO    net.http        contrib/epee/include/storages/http_abstract_invoke.h:53       Failed to invoke http request to  /sendrawtransaction                                
Error sending tx:
2019-01-09 06:28:07,736 ERROR [openmonero] rpc->commit_tx() commit_tx failed                                 
2019-01-09 06:28:07,737 ERROR [openmonero] "Reason not given by daemon." 
```

**Comment by moneroexamples** [comment]
@italocoin-project 

I reply here, as it would be better to conitinue the discussion here in this issue.

From https://github.com/moneroexamples/openmonero/commit/cf4857268125cf32f55c8aea3281574755ea91e6#commitcomment-31879268

> Nice, i will test it and let you know, even tho it must be something with the rpc timeout

It seems so. For some reason this does not work as intended. It should reconnect to the daemon if it is disconnected. 

https://github.com/moneroexamples/openmonero/blob/26bb36e3c8c641ec2bd56d9a5242e014cdaaa7f8/src/RPCCalls.cpp#L93-L101

**Comment by moneroexamples** [comment]
Failure occurs here: https://github.com/monero-project/monero/blob/master/contrib/epee/include/net/net_helper.h#L263

For the following reason

```
2019-01-09 09:38:39.494	    7fd172dc2c00	INFO	net	contrib/epee/include/net/net_helper.h:265	Problems at write: Broken pipe
```

**Comment by italocoin-project** [comment]
Nice, i think that if we first trigher a fake send it will reopen the pipe, and the real one will go true with no problem

**Comment by moneroexamples** [comment]
You can check now. The change is that current blockchain height is obtained using RPC call to monero deamon now, instead of taking it from the blockchain. This serves as a "ping" to the monero daemon not to close the connection due to timeout. And it was timing out, because only submitting txs was done using rpc call. So if the submissions were infrequent, the rpc connection was timing out.

**Comment by italocoin-project** [comment]
"The change is that current blockchain height is obtained using RPC call to monero deamon now, instead of taking it from the blockchain." 
Beutiful! I was working to make a fake call to the RPC and it worked but was another proces that was eating resources and thats why i was looking for another option, but your idea to get the height by calling the rpc is just perfect! Good work, i will test it and let you know, even tho it has to work 100%

Regards

**Comment by moneroexamples** [comment]
thanks. Just let me know how it goes. If this solution works for you as well, then I will have to fix some  unit tests which broke due to this change.

**Comment by italocoin-project** [comment]
Hi,

yes, it works just like expected! Nice work :) 

Regards

**Comment by moneroexamples** [comment]
Good to hear:-) And thanks for the insights about timeout.

**Comment by moneroexamples** [comment]
For reference about timeouts in monero

> The timeounts are N divided by 2 for every extra connection from the same host. N is 30 minutes for local hosts, 5 minutes otherwise. 5 connections should yield 112 second timeouts, which should be more than enough. What RPC are you calling ?


https://github.com/monero-project/monero/issues/5044#issuecomment-452076952

**Comment by moneroexamples** [comment]
I will close the issue. Seems to be solved.
