### ISSUE TITLE
Need more improved decoding address verification logic for integrated address

### ISSUE THREAD

**Issue by talentdeveloper** [moneroexamples/openmonero#124]

**Comment by talentdeveloper** [comment]
When `CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX` and `CRYPTONOTE_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX` are much difference, for example h(245) and G(91), `cnUtil.decode_address()` doesn't work correctly.

https://github.com/moneroexamples/openmonero/blob/1be824a12d803f211a437298cb763aee12e4484c/html/js/cn_util.js#L463

**Comment by moneroexamples** [comment]
Can you provide example of what you mean that it does not work?

Also, the values of these constants correspond to these:

https://github.com/monero-project/monero/blob/d7bac99f6fd1ad8e3f3c90785a3f5b7d77e73cc5/src/cryptonote_config.h#L162-L164

**Comment by talentdeveloper** [comment]
Yes, it's just monero prefix.
Btw, if I use another prefix like I said above, verify decoding logic doesn't work.
I am using forked chain, so the prefix is difference.
`CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX` is 245 (h) and CRYPTONOTE_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX is 91 (G).
In this case, `expectedPrefix.length` is 4 
You can find here.
https://github.com/moneroexamples/openmonero/blob/1be824a12d803f211a437298cb763aee12e4484c/html/js/cn_util.js#L468
On the other hands, `expectedPrefixInt.length` is 2

This is causing the error.

**Comment by moneroexamples** [comment]
Unfortunately, I don't know how it should or should not work in other chains. Probably more changes are required in other places if you change the constants used in monero.

**Comment by talentdeveloper** [comment]
Ok, I see.
One more help needed.
When I try to compile openmonero with `devel` branch, I got compile error like below
`/Work/openmonero/src/MicroCore.h:76:58: error: no matching function for call to ‘cryptonote::BlockchainDB::get_output_key(epee::span<const long unsigned int>, const std::vector<long unsigned int>&, std::vector<cryptonote::output_data_t>&)’
                                 absolute_offsets, outputs);`
Do you have any idea about this?
`get_output_key` declared like below
https://github.com/monero-project/monero/blob/29073f65e8816d4c32b6ffef514943a5650b8d3b/src/blockchain_db/blockchain_db.h#L1314

**Comment by talentdeveloper** [comment]
P/s: it's not other chain, only the prefix is difference with Monero.

**Comment by moneroexamples** [comment]
regarding the prefix. openmonero is also using mymonero code, https://github.com/mymonero/mymonero-core-js, which makes cn_utils.js redundant in parts. The mymoner also defines the prefixes: 
https://github.com/mymonero/mymonero-core-js/blob/master/cryptonote_utils/nettype.js So maybe this also needs to be adjusted?

Similar issue was raised before: https://github.com/moneroexamples/openmonero/issues/108 and I still haven't had time to clean up the legacy code which was replaced by mymonero code.

**Comment by moneroexamples** [comment]
should compile now.

**Comment by moneroexamples** [comment]
Closing as seems to be solved.
