### ISSUE TITLE
Monero v14 hardfork

### ISSUE THREAD

**Issue by SergeyAnkarenko** [moneroexamples/openmonero#139]
Hello, 

What version of openmonero (if it exists) do I need to compile to be up to date with the latest monero fork?

Thank you!

**Comment by moneroexamples** [comment]
`devel` branch or this PR https://github.com/moneroexamples/openmonero/pull/135

**Comment by SergeyAnkarenko** [comment]
```
2019-03-11 13:49:01,111 [I,OM,main.cpp:int main(int, const char**):98] OpenMonero is starting
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is null
Aborted (core dumped)
```

Get this error when running openmonero
(was building against v14.0.0 and v14.0.2, get the same error message)

**Comment by moneroexamples** [comment]
Did you updated `config/config.js` file? Maybe you use older version of the file, with some newer fields missing? https://github.com/moneroexamples/openmonero/blob/master/config/config.json

**Comment by moneroexamples** [comment]
Did you updated your `config/config.json` file? Maybe you use older file with newer fields missing?

https://github.com/moneroexamples/openmonero/blob/master/config/config.json
