### ISSUE TITLE
Remedy "search thread does not exist" errors from api 

### ISSUE THREAD

**Issue by dternyak** [moneroexamples/openmonero#149]
When the api search thread expires due to lack of request activity, it returns:

```
{"reason":"Search thread does not exist.","status":"error"}
```

It would be great to know what the subsequent call should be to refresh this search thread. Will a call to the login endpoint suffice? 

Greatly appreciate your clarification in this! 😁

**Comment by moneroexamples** [comment]
If you use browser client it should not expire, as frontend pulls date from the server every 10 s or so. 

But anyway, you can extend thread's live using this setting: https://github.com/moneroexamples/openmonero/blob/devel/config/config.json#L57

Also do you encounter this issue in `master` or `devel` branch?

**Comment by dternyak** [comment]
It was from the master branch, but we're not using the browser client 😁 

Thank you for the quick response and for the awesome project! This answered it.

**Comment by moneroexamples** [comment]
No problem. Just the heads up. The structure db in `devel` has seen a little change to improve compatibility with MyMonero's fronted. Further db structure updates will also probably happen to accommodate subaddresses. This means that when `devel` branch becomes new `master`,  you will have to update your existing db to match the expected layout.
