### ISSUE TITLE
Calls to `login` endpoint don't refresh search thread

### ISSUE THREAD

**Issue by skubakdj** [moneroexamples/openmonero#153]
I've noticed that if a user has a search thread running, additional calls to `login` do not refresh the search thread timer (whereas calls to other endpoints will keep the thread alive). 

Is this intended behavior, or is it something that might change in future versions?

**Comment by moneroexamples** [comment]
I will check that. Are you using `devel` or `master` branch of OM?

**Comment by skubakdj** [comment]
Currently using the `devel` branch of OM.

**Comment by moneroexamples** [comment]
Will check today. In the meantime, if search threads expire too soon, you can increase their life using this config option:

https://github.com/moneroexamples/openmonero/blob/03d045cd11626b60bacc0205540b8552636f2ad2/config/config.json#L57

**Comment by moneroexamples** [comment]
I added `ping` api call:

https://github.com/moneroexamples/openmonero/tree/devel#ping

It should extend search threads life. It only works if search threads already exists. So if there is no search thread already present, the `ping` won't start it. 

You can check it out, and let me know what you think.

**Comment by skubakdj** [comment]
Thanks for the `ping` call, that looks really useful!

Just to confirm, this the intended behavior for `login` then? Either way is totally fine, I'm just wondering if I need to look out for any future changes.

**Comment by moneroexamples** [comment]
Yes, its separate to `login`. I didn't want to complicated login with ping functionality. 

> I'm just wondering if I need to look out for any future changes.

OM is still in development phase. So changes are possible. Probably the nearest future changes will include  updating database structure to accommodate subaddresses. But don't have time frame for that yet.

**Comment by skubakdj** [comment]
Thanks for the clarification @moneroexamples!
