### ISSUE TITLE
Mymonero Openmonero different tx outputs

### ISSUE THREAD

**Issue by SergeyAnkarenko** [moneroexamples/openmonero#156]
Hello, 

I see different results returned by openmonero and mymonero backends

There is acn account
``address: 43sQLucASFS79csGDt3VYLAfMwMuirz1q4ZYAGNbpfrwX5EYCoXYrtc3rgiwQaSgTv55jMLuKsbAXFJd4A5ovaTJUkU3xUf``

``
view_key: 5C812808575461F61A7547020AD26CFA8E8ADDF1E319278A6DC260BFAA3C2800
``

The account should have only 2 transactions
1. incoming 0.2
2. sent to myself approximately 0.2

![image](https://user-images.githubusercontent.com/6827668/59789084-daea7a80-92d5-11e9-807b-9cffef85d3e7.png)

if I make request to mymonero server
```
curl  -w "\n" -X POST -H "Content-Type: application/json" https://api.mymoner
o.com:8443/get_address_txs -d '{"address": "43sQLucASFS79csGDt3VYLAfMwMuirz1q4ZYAGNbpfrwX5EYCoXYrtc3rgiwQaSgTv55jMLuKsbA
XFJd4A5ovaTJUkU3xUf", "view_key": "5C812808575461F61A7547020AD26CFA8E8ADDF1E319278A6DC260BFAA3C2800"}'
```

returns  set of three transactions
```
'{"address": "43sQLucASFS79csGDt3VYLAfMwMuirz1q4ZYAGNbpfrwX5EYCoXYrtc3rgiwQaSgTv55jMLuKsbA
XFJd4A5ovaTJUkU3xUf", "view_key": "5C812808575461F61A7547020AD26CFA8E8ADDF1E319278A6DC260BFAA3C2800"}'
{"transactions":[{"hash":"d2ac15d397360dd1599255566e43434f7abc00dfcf0a763da0c547a176df0d0e","id":6777009,"timestamp":"2019-06-19T16:27:52Z","total_received":"203688580000","total_sent":"0","unlock_time":0,"height":1860432,"coinbase":false,"mempool":false,"mixin":10},{"hash":"c31a2663d3c2e0ed8809aa286de1e1482ee0713f91aadc72a9e23478dd604cca","id":6777233,"timestamp":"2019-06-19T16:56:37Z","total_received":"203451030000","total_sent":"203688580000","unlock_time":0,"height":1860447,"coinbase":false,"mempool":false,"mixin":10,"spent_outputs":[{"tx_pub_key":"391172e8e6d0cd6ba564e310bd5f222f74d1b3fc8c948a9273f5ba2c87da647a","key_image":"491eaa81eca912fbdd4892060dcece340f296b499af6b252edc7ccc1f2818baf","amount":"203688580000","out_index":1,"mixin":10}]},{"hash":"007936f6915f6d13baefeeb4f3a558ff951855e6febebc7dc112a638beaa067c","id":6777303,"timestamp":"2019-06-19T17:01:24Z","total_received":"0","total_sent":"203688580000","unlock_time":0,"height":1860452,"coinbase":false,"mempool":false,"mixin":10,"payment_id":"0b420367de30f81b3efe76f170b271fd2931e148a6fc22691234567890abf984","spent_outputs":[{"tx_pub_key":"391172e8e6d0cd6ba564e310bd5f222f74d1b3fc8c948a9273f5ba2c87da647a","key_image":"1348c4a0afb54bcd25d2a2cd6d05fea46ce41175343337c3ae1d0778bb1f2a5f","amount":"203688580000","out_index":1,"mixin":10}]}],"total_received":"407139610000","scanned_height":6777252,"scanned_block_height":1860447,"start_height":6776879,"transaction_height":6777303,"blockchain_height":1860452}
```

![image](https://user-images.githubusercontent.com/6827668/59790035-b0012600-92d7-11e9-8310-442a3f89f925.png)

if I make request to openmonero server
```
curl  -w "\n" -X POST http://40.77.99.22:1984/get_address_txs -d '{"address": "43sQLucASFS79csGDt3VYLAfMwMuirz1q4ZYAGNbpfrwX5EYCoXYrtc3rgiwQaSgTv55jMLuKsbAXFJd4A5ovaTJUkU3xUf", "view_key": "5C812808575461F61A7547020AD26CFA8E8ADDF1E319278A6DC260BFAA3C2800"}'
```

I get set of two transactions
```
{"blockchain_height":1860463,"new_address":false,"scanned_block_height":1860456,"scanned_block_timestamp":1560964023,"scanned_height":0,"start_height":1859776,"status":"success","total_received":"407139610000","total_received_unlocked":"407139610000","transactions":[{"coinbase":false,"hash":"d2ac15d397360dd1599255566e43434f7abc00dfcf0a763da0c547a176df0d0e","height":1860432,"id":6640890,"mempool":false,"mixin":11,"payment_id":"1f01262e768cac79","timestamp":1560961672000,"total_received":"203688580000","total_sent":0,"tx_pub_key":"391172e8e6d0cd6ba564e310bd5f222f74d1b3fc8c948a9273f5ba2c87da647a","unlock_time":1860442},{"coinbase":false,"hash":"c31a2663d3c2e0ed8809aa286de1e1482ee0713f91aadc72a9e23478dd604cca","height":1860447,"id":6641114,"mempool":false,"mixin":11,"payment_id":"3b0d43302421ccec","timestamp":1560963397000,"total_received":"203451030000","total_sent":0,"tx_pub_key":"669581134f4093bf5c4c6833c730a24be2e95a3a8867458aa4e447df49b4917c","unlock_time":1860457}]}
```

How to explain it. It's very strange. I suspect, it's related to monero private feature and I will filter mymonero transaction list using key images and I will be ok, but how to explain different values of
`total_received` property?

Thank you

**Comment by SergeyAnkarenko** [comment]
This is the version of open monero I am running
```
{"api":65541,"blockchain_height":1860465,"git_branch_name":"master","last_git_commit_date":"2019-05-21","last_git_commit_hash":"9607cc2","monero_version_full":"0.14.0.2-8039b8d","network_type":0,"testnet":false}
```

**Comment by SergeyAnkarenko** [comment]
If you look at transaction with hash in openmonero
`c31a2663d3c2e0ed8809aa286de1e1482ee0713f91aadc72a9e23478dd604cca`

```
{
      "coinbase": false,
      "hash": "c31a2663d3c2e0ed8809aa286de1e1482ee0713f91aadc72a9e23478dd604cca",
      "height": 1860447,
      "id": 6641114,
      "mempool": false,
      "mixin": 11,
      "payment_id": "3b0d43302421ccec",
      "timestamp": 1560963397000,
      "total_received": "203451030000",
      "total_sent": 0,
      "tx_pub_key": "669581134f4093bf5c4c6833c730a24be2e95a3a8867458aa4e447df49b4917c",
      "unlock_time": 1860457
    }
```

You will see `"total_received": "203451030000"` and `"total_sent": 0`

But if you go to mymonero
```
"hash": "c31a2663d3c2e0ed8809aa286de1e1482ee0713f91aadc72a9e23478dd604cca",
      "id": 6777233,
      "timestamp": "2019-06-19T16:56:37Z",
      "total_received": "203451030000",
      "total_sent": "203688580000",
      "unlock_time": 0,
      "height": 1860447,
      "coinbase": false,
      "mempool": false,
      "mixin": 10,
      "spent_outputs": [
        {
          "tx_pub_key": "391172e8e6d0cd6ba564e310bd5f222f74d1b3fc8c948a9273f5ba2c87da647a",
          "key_image": "491eaa81eca912fbdd4892060dcece340f296b499af6b252edc7ccc1f2818baf",
          "amount": "203688580000",
          "out_index": 1,
          "mixin": 10
        }
      ]
```

You will see a different result 
``
``

**Comment by moneroexamples** [comment]
Looking into it. Can you check what happens when you click on the transaction in question and then on  "more details"? The more details has funny bug that it will actually try to estimate the spending of a tx, even in view-only mode (when spend key is not given). 

I did this in view only mode, and the result is below. Just want to check if you have same?

![Screenshot_20190620_073844](https://user-images.githubusercontent.com/15305358/59808541-49a7f200-932f-11e9-91a0-2bcb2219fabd.png)

If you have same result, this will indicate that OM correctly detected the spending, though for some reason it does not get accounted for in normal OM mode.

**Comment by SergeyAnkarenko** [comment]
![image](https://user-images.githubusercontent.com/6827668/59808891-e1ddb100-9306-11e9-8fca-1c12bc2038a7.png)

**Comment by SergeyAnkarenko** [comment]
Amount is different

**Comment by moneroexamples** [comment]
And can you login in view-only mode? Go to `login` and then `login with address and viewkey`, and just provide address and viewkey (no spend key). 

And branch of OM is `devel` or `master`?

**Comment by SergeyAnkarenko** [comment]
I will try to remove blockchain and synchronize again. My another node (which is a little bit older) display information correctely

This is `master`  (https://github.com/moneroexamples/openmonero/commit/9607cc2c69b66727c10705a604970ce65e37a89a)
![image](https://user-images.githubusercontent.com/6827668/59809321-be1b6a80-9308-11e9-9f28-a44ee368a74c.png)

**Comment by moneroexamples** [comment]
Master has been seen a major updated few days ago. You are currently using version from  May 21, 2019. So I would recommend trying latest version. Please note, mysql db must be updated as well as new field was added to improve countability with mymonero official fronted.

**Comment by SergeyAnkarenko** [comment]
Is it possible to update mysql table structure without changing their content? Could you give an advise on how to migrate to updated mysql db?

**Comment by SergeyAnkarenko** [comment]
Also I have noticed, that I run development build, how can I switch to production
![image](https://user-images.githubusercontent.com/6827668/59809874-51ee3600-930b-11e9-8235-2c6b75b25747.png)

**Comment by moneroexamples** [comment]
There is no production version, everything is development. `master` branch is basically a snapshot of `devel` branch made at a time when new monero gets released. So recently monero v0.14.1 was released, and `master` was updated from `devel` branch.

**Comment by SergeyAnkarenko** [comment]
Ok, I have been experimenting with openmonero for a while, and it seems very strange for me. Maybe I have done something wrong or forbidden, so I will describe, what I did

1. I waited until monero synchronizes
2. Added manually record into Accounts mysql table

```
INSERT INTO Accounts VALUES (1667,'43sQLucASFS79csGDt3VYLAfMwMuirz1q4ZYAGNbpfrwX5EYCoXYrtc3rgiwQaSgTv55jMLuKsbAXFJd4A5ovaTJUkU3xUf','ea9eea25076eef804a2e1cbd217fc0d52cde1f650a4fda0ca2415fa105b167c1',1772787,'2019-02-16 15:30:33',1860430,'2019-06-19 16:09:53','2019-06-19 16:09:53', '0')
```
notice, scanned_block_height is set to `1860430`, because the very first transaction related to this account was mined in [1860432](https://moneroblocks.info/search/d2ac15d397360dd1599255566e43434f7abc00dfcf0a763da0c547a176df0d0e) block

3. Then I invoked the login function to create txSearch thread and let it synchronize account a little bit
```
 curl  -w "\n" -X POST  http://52.188.188.184:1984/login -d '{"create_account": true, "address": "43sQLucASFS79csGDt3VYLAfMwMuirz1q4ZYAGNbpfrwX5EYCoXYrtc3rgiwQaSgTv55jMLuKsbAXFJd4A5ovaTJUkU3xUf", "v
iew_key": "5C812808575461F61A7547020AD26CFA8E8ADDF1E319278A6DC260BFAA3C2800"}' 
```

4. So I see **wrong balance**
![image](https://user-images.githubusercontent.com/6827668/60027509-48b3ef00-96a6-11e9-95ba-6df6c2ca4b53.png)

This is **right balance**
![image](https://user-images.githubusercontent.com/6827668/60027669-8dd82100-96a6-11e9-9367-30e4d12c39ad.png)


You can navigate to either http://52.188.188.184 and  https://wallet.mymonero.com and test it yourself
I tested on different machines, I tested different versions of openmonero, including teh most recent one. So I completely don't understand, whats is going on

PS. If you want I can send you private key for this account so you can test it

**Comment by SergeyAnkarenko** [comment]
I tried the most recent version of openmonero 
https://github.com/moneroexamples/openmonero/commit/57bd8d523b4748d6dbd8a5de2cf3768c238e87f0

problem has disappeared
