### ISSUE TITLE
error: cannot convert 'boost::optional<epee::mlocked

### ISSUE THREAD

**Issue by italocoin-project** [moneroexamples/openmonero#162]
i tried to compile the master and devel and i still get this error:

`/root/openmonero/src/xmregcore/src/Account.h: In member function 'const auto& xmreg::Account::keys()':
/root/openmonero/src/xmregcore/src/Account.h:93:32: error: cannot convert 'boost::optional<epee::mlocked<tools::scrubbed<crypto::ec_scalar> > >' to 'bool' in initialization
             assert(bool{viewkey});
                                ^
/root/openmonero/src/xmregcore/src/UniversalIdentifier.cpp: In member function 'virtual void xmreg::Output::identify(const cryptonote::transaction&, const crypto::public_key&, const std::vector<crypto::public_key>&)':
/root/openmonero/src/xmregcore/src/UniversalIdentifier.cpp:179:44: error: cannot convert 'std::unique_ptr<cryptonote::subaddress_index>' to 'bool' in initialization
             mine_output = bool {subaddr_idx};
                                            ^
/root/openmonero/src/xmregcore/src/UniversalIdentifier.cpp:201:48: error: cannot convert 'std::unique_ptr<cryptonote::subaddress_index>' to 'bool' in initialization
                 mine_output = bool {subaddr_idx};`

**Comment by moneroexamples** [comment]
Which linux distro?

**Comment by italocoin-project** [comment]
Ubuntu 16.4

**Comment by moneroexamples** [comment]
Did you install newer compiler on ubuntu 16.04? Default gcc and clang icompilers in ubuntu 16.04 are too old. OM requires C++14 compatible compilers. You can install newer versions of the compilers using the procedure shown here if you want: https://github.com/moneroexamples/openmonero/issues/89#issuecomment-410409361

**Comment by italocoin-project** [comment]
Ohh, I forgot about that, latter on i'll test it and I will get back to let you know, thank you

**Comment by italocoin-project** [comment]
Hi, so it was c++14 the issue on compilation, but now i get another issue wich is this

`2019-07-25 07:38:17,726 I 4BMaE8: address does not exists
2019-07-25 07:38:17,727 I create_if_notfound is false
2019-07-25 07:38:17,819 E 4BMaE8: login_and_start_search_thread failed. {"generated_locally":false,"start_height":xxxx}
`

and of course this erro on frontend

`An error occured in fetchTransactions: Search thread does not exist.`

any idea?

**Comment by italocoin-project** [comment]
Hi @moneroexamples  ,
i would have a question if possible, i see here a demo of a new template but it is not available in this repo, do i need to download it from somewhere else?

`http://139.162.60.17:8100 - MyMonero frontend`

**Comment by moneroexamples** [comment]
The upstream version of mymonero frontend is: https://github.com/mymonero/mymonero-app-js

The frontend for the mainnet should work out of the box with openmonero if you have OM running with ssl encryption (https). Would have to double check this as up until recently I did not have ssl certificates. For stagenet or no ssl, tiny modification are needed in the mymonero code. 

If you are interested in using the mymonero frontend, I can give more detailed instructions as I don't have them written anywhere for now.

**Comment by italocoin-project** [comment]
I would like to test it out, if you can give more detailed instructions that would be really appreciated :) thank you

**Comment by moneroexamples** [comment]
To get and start the stock version (it works only with Mainnet and ssl) of the frontend: 

#### Basic setup

```bash
git clone --recurse-submodules https://github.com/mymonero/mymonero-app-js

cd mymonero-app-js

npm install

./bin/start_dev_desktop
```
And in the settings of the app, you can specify custom server, in this case address for openmonero backend.

#### Stagenet and no ssl

The requirement for mainnet and ssl are hardcoded into mymonero client. Thus it needs to be manually modified to make it work with stagenet openmonero without any ssl. The following three edits should be sufficient:

Set to stagenet in `index_context.electron.renderer.js`:

```diff
--- a/local_modules/MainWindow/Models/index_context.electron.renderer.js
+++ b/local_modules/MainWindow/Models/index_context.electron.renderer.js
@@ -165,7 +165,7 @@ function NewHydratedContext(
 ) {
        var initialContext =
        {
-               nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.MAINNET, // critical setting
+               nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.STAGENET, // critical setting
                app: app,
                menuController: menuController,
                appUpdatesController: appUpdatesController,
@@ -190,4 +190,4 @@ function NewHydratedContext(
                initialContext
        )
 }
```

Set to stagenet in `index.browser.js`:

```diff
--- a/local_modules/MainWindow/Views/index.browser.js
+++ b/local_modules/MainWindow/Views/index.browser.js
@@ -66,7 +66,7 @@ window.BootApp = function()
        require('../../mymonero_libapp_js/libapp_js/MyMoneroLibAppBridge')({}).then(function(coreBridge_instance) // we can just use this directly in the browser version
        {
                const context = require('../Models/index_context.browser').NewHydratedContext({
-                       nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.MAINNET, // critical setting
+                       nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.STAGENET, // critical setting
                        app: app,
                        isDebug: isDebug,
                        isLiteApp: true, // used sparingly for to disable (but not redact) functionality
@@ -137,4 +137,4 @@ window.BootApp = function()
                throw e
        });
 }
```
Disable ssl/https in net_service_utils.js:

```diff
--- a/hostAPI/net_service_utils.js
+++ b/hostAPI/net_service_utils.js
@@ -92,7 +92,7 @@ exports.HTTPRequest = HTTPRequest;
 function _new_APIAddress_baseURLString(
        apiAddress_authority, // authority means [subdomain.]host.…[:…]
 ) {
-       return "https" + "://" + apiAddress_authority + "/";
+       return "http" + "://" + apiAddress_authority + "/";
 }
 function _new_requestOptions_base(methodName, completeURL, json_parameters) {
        return {
```

And now you can specify just an IP and port for openmonero in the settings of the app when it starts. For default localhost OM uses `127.0.0.1:1984`

So this should be enough to make the mymonero app work with OM on stagenet without any ssl conectoin. The only issue I've encountered is for non-free importing existing wallets. 

Please let me know how it goes.

**Comment by italocoin-project** [comment]
> To get and start the stock version (it works only with Mainnet and ssl) of the frontend:
> 
> ```shell
> git clone --recurse-submodules https://github.com/mymonero/mymonero-app-js
> 
> cd mymonero-app-js
> 
> npm install
> 
> ./bin/start_dev_desktop
> ```
> 
> And in the settings of the app, you can specify custom server, in this case address for openmonero backend.
> 
> ##### Stagenet and no ssl
> The requirement for mainnet and ssl are hardcoded into mymonero client. Thus it needs to be manually modified to make it work with stagenet openmonero without any ssl. The following three edits should be sufficient:
> 
> Set to stagenet in `index_context.electron.renderer.js`:
> 
> ```diff
> --- a/local_modules/MainWindow/Models/index_context.electron.renderer.js
> +++ b/local_modules/MainWindow/Models/index_context.electron.renderer.js
> @@ -165,7 +165,7 @@ function NewHydratedContext(
>  ) {
>         var initialContext =
>         {
> -               nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.MAINNET, // critical setting
> +               nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.STAGENET, // critical setting
>                 app: app,
>                 menuController: menuController,
>                 appUpdatesController: appUpdatesController,
> @@ -190,4 +190,4 @@ function NewHydratedContext(
>                 initialContext
>         )
>  }
> ```
> 
> Set to stagenet in `index.browser.js`:
> 
> ```diff
> --- a/local_modules/MainWindow/Views/index.browser.js
> +++ b/local_modules/MainWindow/Views/index.browser.js
> @@ -66,7 +66,7 @@ window.BootApp = function()
>         require('../../mymonero_libapp_js/libapp_js/MyMoneroLibAppBridge')({}).then(function(coreBridge_instance) // we can just use this directly in the browser version
>         {
>                 const context = require('../Models/index_context.browser').NewHydratedContext({
> -                       nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.MAINNET, // critical setting
> +                       nettype: require('../../mymonero_libapp_js/mymonero-core-js/cryptonote_utils/nettype').network_type.STAGENET, // critical setting
>                         app: app,
>                         isDebug: isDebug,
>                         isLiteApp: true, // used sparingly for to disable (but not redact) functionality
> @@ -137,4 +137,4 @@ window.BootApp = function()
>                 throw e
>         });
>  }
> ```
> 
> Disable ssl/https in `net_service_utils.js`:
> 
> ```diff
> --- a/hostAPI/net_service_utils.js
> +++ b/hostAPI/net_service_utils.js
> @@ -92,7 +92,7 @@ exports.HTTPRequest = HTTPRequest;
>  function _new_APIAddress_baseURLString(
>         apiAddress_authority, // authority means [subdomain.]host.…[:…]
>  ) {
> -       return "https" + "://" + apiAddress_authority + "/";
> +       return "http" + "://" + apiAddress_authority + "/";
>  }
>  function _new_requestOptions_base(methodName, completeURL, json_parameters) {
>         return {
> ```
> 
> And now you can specify just an IP and port for openmonero in the settings of the app when it starts. For default localhost OM uses `127.0.0.1:1984`
> 
> So this should be enough to make the mymonero app work with OM on stagenet without any ssl conectoin. The only issue I've encountered is for non-free importing existing wallets.
> 
> Please let me know how it goes.

Thank you very much, sorry for late reply i didn't got the notification, i will test it out and let you know, thanks again!
