### ISSUE TITLE
mysqlpp :  undefined reference error

### ISSUE THREAD

**Issue by sanada08** [moneroexamples/openmonero#164]
```/usr/bin/ld: src/libmyxrm.a(MySqlConnector.cpp.o): in function `xmreg::MySqlConnector::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
MySqlConnector.cpp:(.text+0x305): undefined reference to `mysqlpp::Connection::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `xmreg::MysqlOutpus::exist(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, xmreg::XmrOutput&)':
MySqlAccounts.cpp:(.text+0x457): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `xmreg::MysqlTransactions::exist(unsigned long const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, xmreg::XmrTransaction&)':
MySqlAccounts.cpp:(.text+0xb6e): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `xmreg::MysqlPayments::select_by_payment_id(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<xmreg::XmrPayment, std::allocator<xmreg::XmrPayment> >&)':
MySqlAccounts.cpp:(.text+0x1108): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `xmreg::MySqlAccounts::select(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, xmreg::XmrAccount&)':
MySqlAccounts.cpp:(.text+0x1577): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `void xmreg::populate_Accounts<(mysqlpp::sql_dummy_type)0>(xmreg::Accounts*, mysqlpp::Row const&)':
MySqlAccounts.cpp:(.text._ZN5xmreg17populate_AccountsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_8AccountsERKNS1_3RowE[_ZN5xmreg17populate_AccountsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_8AccountsERKNS1_3RowE]+0xdd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mysqlpp::String::conv<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/usr/bin/ld: MySqlAccounts.cpp:(.text._ZN5xmreg17populate_AccountsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_8AccountsERKNS1_3RowE[_ZN5xmreg17populate_AccountsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_8AccountsERKNS1_3RowE]+0x159): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mysqlpp::String::conv<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `void xmreg::populate_Transactions<(mysqlpp::sql_dummy_type)0>(xmreg::Transactions*, mysqlpp::Row const&)':
MySqlAccounts.cpp:(.text._ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE[_ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE]+0xdf): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mysqlpp::String::conv<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/usr/bin/ld: MySqlAccounts.cpp:(.text._ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE[_ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE]+0x15b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mysqlpp::String::conv<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/usr/bin/ld: MySqlAccounts.cpp:(.text._ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE[_ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE]+0x1d7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mysqlpp::String::conv<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o):MySqlAccounts.cpp:(.text._ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE[_ZN5xmreg21populate_TransactionsILN7mysqlpp14sql_dummy_typeE0EEEvPNS_12TransactionsERKNS1_3RowE]+0x46e): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mysqlpp::String::conv<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const' follow
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `void mysqlpp::Query::storein<std::vector<xmreg::XmrTransaction, std::allocator<xmreg::XmrTransaction> > >(std::vector<xmreg::XmrTransaction, std::allocator<xmreg::XmrTransaction> >&, mysqlpp::SQLQueryParms&)':
MySqlAccounts.cpp:(.text._ZN7mysqlpp5Query7storeinISt6vectorIN5xmreg14XmrTransactionESaIS4_EEEEvRT_RNS_13SQLQueryParmsE[_ZN7mysqlpp5Query7storeinISt6vectorIN5xmreg14XmrTransactionESaIS4_EEEEvRT_RNS_13SQLQueryParmsE]+0x28): undefined reference to `mysqlpp::Query::str[abi:cxx11](mysqlpp::SQLQueryParms&)'
/usr/bin/ld: MySqlAccounts.cpp:(.text._ZN7mysqlpp5Query7storeinISt6vectorIN5xmreg14XmrTransactionESaIS4_EEEEvRT_RNS_13SQLQueryParmsE[_ZN7mysqlpp5Query7storeinISt6vectorIN5xmreg14XmrTransactionESaIS4_EEEEvRT_RNS_13SQLQueryParmsE]+0x40): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `std::ostream& xmreg::operator<< <mysqlpp::quote_type0>(std::ostream&, xmreg::Accounts_value_list<mysqlpp::quote_type0> const&)':
MySqlAccounts.cpp:(.text._ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_19Accounts_value_listIT_EE[_ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_19Accounts_value_listIT_EE]+0xd4): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: MySqlAccounts.cpp:(.text._ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_19Accounts_value_listIT_EE[_ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_19Accounts_value_listIT_EE]+0x151): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o): in function `std::ostream& xmreg::operator<< <mysqlpp::quote_type0>(std::ostream&, xmreg::Transactions_value_list<mysqlpp::quote_type0> const&)':
MySqlAccounts.cpp:(.text._ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_23Transactions_value_listIT_EE[_ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_23Transactions_value_listIT_EE]+0xd4): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: MySqlAccounts.cpp:(.text._ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_23Transactions_value_listIT_EE[_ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_23Transactions_value_listIT_EE]+0x151): undefined reference to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: src/libmyxrm.a(MySqlAccounts.cpp.o):MySqlAccounts.cpp:(.text._ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_23Transactions_value_listIT_EE[_ZN5xmreglsIN7mysqlpp11quote_type0EEERSoS3_RKNS_23Transactions_value_listIT_EE]+0x1ce): more undefined references to `mysqlpp::SQLTypeAdapter::SQLTypeAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)' follow
collect2: error: ld returned 1 exit status```

Please help me with this issue.

**Comment by moneroexamples** [comment]
Hi. Could you specify which OS and which monero and openmonero branches are you using? Also have you install `mysqlpp` libraries for your OS?

**Comment by sanada08** [comment]
Using kali linux , monero 0.14  and master branch of openmonero

**Comment by moneroexamples** [comment]
Seems `mysql++` or Kali linux equivalent to it is missing, or located somewhere in the system where openmonero can't find it. All missing references are to mysql c++ library.

**Comment by moneroexamples** [comment]
> Suddenly I got this error,

Could you clarify what you mean, by "Suddenly"? So before now, OM compiled fine once mysql++ was installed?

**Comment by sanada08** [comment]
After installing mysql++, I have removed old build files and started to build again. I struct with above error.

**Comment by moneroexamples** [comment]
Which Kali linux do you use? I tried `Kali GNU/Linux Rolling` which has gcc 9.2 and haven't experienced the build issue? I speculate that because OM is C++14, you use older version and thus not fully compatible with C++14?

**Comment by sanada08** [comment]
using the same kali linux with gcc 8.3.

**Comment by moneroexamples** [comment]
gcc 8.3 should be enough. I don't know at the moment what's happening. Were do I get kali linux with gcc 8.3? I can try to replicate the issue on exactly same version of kali you have. What I used  earlier was newer kali than yours.

**Comment by sanada08** [comment]
I have fixed this issue by replicated in ubuntu. thanks
