### ISSUE TITLE
add Dockerfile

### ISSUE THREAD

**Issue by intosKai** [moneroexamples/openmonero#166]
Will be nice add Dockerfile for fast building and start openmonero

**Comment by moneroexamples** [comment]
Yes, it could be useful, but at present I don't have plan for that to do it myself.  If you want you can give it a go and try to create one for OM.

**Comment by intosKai** [comment]
Can you provide the all libraries for build (for ubuntu, or another unix-like system)? Now I'm stacks on this error:
`[ 87%] Built target myxmr Scanning dependencies of target openmonero 
[ 90%] Building CXX object CMakeFiles/openmonero.dir/main.cpp.o make
[2]: *** No rule to make target 'Xmr_CRYPTONOTE_CORE_LIBRARY-NOTFOUND', needed by 'openmonero'. Stop. CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/openmonero.dir/all' failed make
[1]: *** [CMakeFiles/openmonero.dir/all] Error 2 Makefile:83: recipe for target 'all' failed make: *** 
[all] Error 2`
Monero daemon is in ~/monero

**Comment by moneroexamples** [comment]
Which branch of open monero do you use, and which ubuntu?

**Comment by intosKai** [comment]
Master branch, Ubuntu 18.04

**Comment by moneroexamples** [comment]
OM hasn't been yet adopted to work with upcoming version of monero with randomx. I will try to fix that.

**Comment by intosKai** [comment]
But I'm use 0.14.1.2 version of Monero

**Comment by intosKai** [comment]
Just give me an info about how to build OM: which OS with libraries I need. I will solve other problems myself.

**Comment by moneroexamples** [comment]
I see. I will try to check it on ubuntu 18.04. But from the error message you posted it seems OM can find monero `'Xmr_CRYPTONOTE_CORE_LIBRARY-NOTFOUND',`.

Have you compiled monero with `USE_SINGLE_BUILDDIR` flag as shown here https://github.com/moneroexamples/monero-compilation/blob/master/README.md#example-compilation-of-monero-on-ubuntu-1804

p.s.
Today I'm unable to look much into it if the above does not help.

**Comment by intosKai** [comment]
Yes, this is my mistake. Compile with ```USE_SINGLE_BUILDDIR``` helps me.
