### ISSUE TITLE
"make" compilation error on VPS_Ubuntu_18.04

### ISSUE THREAD

**Issue by M-Adeel-Danish** [moneroexamples/openmonero#167]
Hi support@monero, thanks for your great service.

I have successfull installed monero service, daemon is synced and running. OS: Ubuntu 18.04.1 LTS, running on VPS. However I am facing issues compiling openmonero. I have tried changing updating compiler version with no results. 

Kindly take a look what I am doing wrong.
Thank you!

[cmake-log.txt](https://github.com/moneroexamples/openmonero/files/3865845/cmake-log.txt)
[make -j4-log.txt](https://github.com/moneroexamples/openmonero/files/3865848/make.-j4-log.txt)

**Comment by M-Adeel-Danish** [comment]
`monero@server:~/openmonero/build$ make -j4
Scanning dependencies of target restbed
Scanning dependencies of target myxrmcore
[  3%] Creating directories for 'restbed'
[  6%] Building CXX object src/xmregcore/src/CMakeFiles/myxrmcore.dir/MicroCore.cpp.o
[  9%] Building CXX object src/xmregcore/src/CMakeFiles/myxrmcore.dir/UniversalIdentifier.cpp.o
[ 12%] Building CXX object src/xmregcore/src/CMakeFiles/myxrmcore.dir/tools.cpp.o
[ 15%] No download step for 'restbed'
[ 18%] No patch step for 'restbed'
[ 21%] No update step for 'restbed'
[ 25%] Performing configure step for 'restbed'
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
   Copyright 2013-2017, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: /home/monero/openmonero/ext/restbed/dependency/asio/asio/include
-- Found Kashmir include at: /home/monero/openmonero/ext/restbed/dependency/kashmir
-- Configuring done
-- Generating done
-- Build files have been written to: /home/monero/openmonero/build/restbed_build/src/restbed-build
[ 28%] Performing build step for 'restbed'
Scanning dependencies of target restbed
[  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o
[  9%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/rule.cpp.o
[ 14%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o
[ 19%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o
[ 23%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o
[ 28%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/service.cpp.o
[ 33%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/session.cpp.o
[ 31%] Building CXX object src/xmregcore/src/CMakeFiles/myxrmcore.dir/Account.cpp.o
[ 38%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/resource.cpp.o
[ 42%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/response.cpp.o
[ 47%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/settings.cpp.o
[ 52%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket.cpp.o
[ 57%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/ssl_settings.cpp.o
[ 61%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/session_manager.cpp.o
[ 66%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/http_impl.cpp.o
[ 71%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket_message.cpp.o
[ 76%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/socket_impl.cpp.o
[ 80%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/service_impl.cpp.o
[ 85%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/session_impl.cpp.o
[ 90%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_impl.cpp.o
[ 95%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_manager_impl.cpp.o
[100%] Linking CXX static library librestbed.a
[100%] Built target restbed
[ 34%] Performing install step for 'restbed'
[100%] Built target restbed
Install the project...
-- Install configuration: ""
-- Installing: /home/monero/openmonero/build/distribution/include/restbed
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/uri.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/byte.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/http.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/rule.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/common.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/string.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/logger.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/request.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/service.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/session.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/settings.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/response.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/resource.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/web_socket.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/status_code.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/ssl_settings.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/context_value.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/session_manager.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/web_socket_message.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/context_placeholder.hpp
-- Installing: /home/monero/openmonero/build/distribution/include/corvusoft/restbed/context_placeholder_base.hpp
-- Installing: /home/monero/openmonero/build/distribution/library/librestbed.a
[ 37%] Completed 'restbed'
[ 37%] Built target restbed
[ 40%] Linking CXX static library libmyxrmcore.a
[ 40%] Built target myxrmcore
Scanning dependencies of target myxmr
Scanning dependencies of target xmregcore_example
make[2]: *** No rule to make target 'Xmr_CRYPTONOTE_CORE_LIBRARY-NOTFOUND', needed by 'src/xmregcore/xmregcore_example'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object src/xmregcore/CMakeFiles/xmregcore_example.dir/example.cpp.o
[ 46%] Building CXX object src/CMakeFiles/myxmr.dir/CurrentBlockchainStatus.cpp.o
[ 50%] Building CXX object src/CMakeFiles/myxmr.dir/CmdLineOptions.cpp.o
[ 53%] Building CXX object src/CMakeFiles/myxmr.dir/db/MySqlConnector.cpp.o
[ 56%] Building CXX object src/CMakeFiles/myxmr.dir/db/MySqlAccounts.cpp.o
[ 59%] Building CXX object src/CMakeFiles/myxmr.dir/db/ssqlses.cpp.o
[ 62%] Building CXX object src/CMakeFiles/myxmr.dir/OpenMoneroRequests.cpp.o
In file included from /home/monero/monero/contrib/epee/include/misc_log_ex.h:35,
                 from /home/monero/monero/contrib/epee/include/net/net_utils_base.h:39,
                 from /home/monero/monero/contrib/epee/include/net/net_helper.h:48,
                 from /home/monero/monero/contrib/epee/include/net/http_client.h:41,
                 from /home/monero/openmonero/src/xmregcore/src/monero_headers.h:22,
                 from /home/monero/openmonero/src/xmregcore/src/MicroCore.h:8,
                 from /home/monero/openmonero/src/CurrentBlockchainStatus.h:6,
                 from /home/monero/openmonero/src/CurrentBlockchainStatus.cpp:5:
/home/monero/openmonero/src/CurrentBlockchainStatus.cpp: In member function ‘virtual void xmreg::CurrentBlockchainStatus::monitor_blockchain()’:
/home/monero/openmonero/src/om_log.h:10:18: error: no matching function for call to ‘el::base::Writer::Writer(el::Level, const char [56], int, const char [66], el::base::DispatchAction, int)’
 #define OMVLOG1  CVLOG(1, OPENMONERO_LOG_CATEGORY)
                  ^~~~~
/home/monero/openmonero/src/CurrentBlockchainStatus.cpp:49:12: note: in expansion of macro ‘OMVLOG1’
            OMVLOG1 << "PoolQueue size: "
            ^~~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note: candidate: ‘el::base::Writer::Writer(el::LogMessage*, el::base::DispatchAction)’
   Writer(LogMessage* msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) :
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note:   candidate expects 2 arguments, 6 provided
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note: candidate: ‘el::base::Writer::Writer(el::Level, el::Color, const char*, el::base::type::LineNumber, const char*, el::base::DispatchAction, el::base::type::VerboseLevel)’
   Writer(Level level, Color color, const char* file, base::type::LineNumber line,
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note:   no known conversion for argument 2 from ‘const char [56]’ to ‘el::Color’
[ 65%] Building CXX object src/CMakeFiles/myxmr.dir/TxSearch.cpp.o
CMakeFiles/Makefile2:162: recipe for target 'src/xmregcore/CMakeFiles/xmregcore_example.dir/all' failed
make[1]: *** [src/xmregcore/CMakeFiles/xmregcore_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Building CXX object src/CMakeFiles/myxmr.dir/RPCCalls.cpp.o
src/CMakeFiles/myxmr.dir/build.make:86: recipe for target 'src/CMakeFiles/myxmr.dir/CurrentBlockchainStatus.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxmr.dir/CurrentBlockchainStatus.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/monero/monero/contrib/epee/include/misc_log_ex.h:35,
                 from /home/monero/monero/contrib/epee/include/net/net_utils_base.h:39,
                 from /home/monero/monero/contrib/epee/include/net/net_helper.h:48,
                 from /home/monero/monero/contrib/epee/include/net/http_client.h:41,
                 from /home/monero/openmonero/src/xmregcore/src/monero_headers.h:22,
                 from /home/monero/openmonero/src/db/../utils.h:16,
                 from /home/monero/openmonero/src/db/MySqlAccounts.h:8,
                 from /home/monero/openmonero/src/TxSearch.h:3,
                 from /home/monero/openmonero/src/TxSearch.cpp:7:
/home/monero/openmonero/src/TxSearch.cpp: In member function ‘virtual void xmreg::TxSearch::operator()()’:
/home/monero/openmonero/src/om_log.h:10:18: error: no matching function for call to ‘el::base::Writer::Writer(el::Level, const char [41], int, const char [43], el::base::DispatchAction, int)’
 #define OMVLOG1  CVLOG(1, OPENMONERO_LOG_CATEGORY)
                  ^~~~~
/home/monero/openmonero/src/TxSearch.cpp:112:9: note: in expansion of macro ‘OMVLOG1’
         OMVLOG1 << address_prefix << ": waiting for new block. "
         ^~~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note: candidate: ‘el::base::Writer::Writer(el::LogMessage*, el::base::DispatchAction)’
   Writer(LogMessage* msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) :
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note:   candidate expects 2 arguments, 6 provided
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note: candidate: ‘el::base::Writer::Writer(el::Level, el::Color, const char*, el::base::type::LineNumber, const char*, el::base::DispatchAction, el::base::type::VerboseLevel)’
   Writer(Level level, Color color, const char* file, base::type::LineNumber line,
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note:   no known conversion for argument 2 from ‘const char [41]’ to ‘el::Color’
/home/monero/openmonero/src/om_log.h:11:18: error: no matching function for call to ‘el::base::Writer::Writer(el::Level, const char [41], int, const char [43], el::base::DispatchAction, int)’
 #define OMVLOG2  CVLOG(2, OPENMONERO_LOG_CATEGORY)
                  ^~~~~
/home/monero/openmonero/src/TxSearch.cpp:147:1: note: in expansion of macro ‘OMVLOG2’
 OMVLOG2 << address_prefix  + ": analyzing "
 ^~~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note: candidate: ‘el::base::Writer::Writer(el::LogMessage*, el::base::DispatchAction)’
   Writer(LogMessage* msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) :
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note:   candidate expects 2 arguments, 6 provided
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note: candidate: ‘el::base::Writer::Writer(el::Level, el::Color, const char*, el::base::type::LineNumber, const char*, el::base::DispatchAction, el::base::type::VerboseLevel)’
   Writer(Level level, Color color, const char* file, base::type::LineNumber line,
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note:   no known conversion for argument 2 from ‘const char [41]’ to ‘el::Color’
/home/monero/openmonero/src/om_log.h:10:18: error: no matching function for call to ‘el::base::Writer::Writer(el::Level, const char [41], int, const char [43], el::base::DispatchAction, int)’
 #define OMVLOG1  CVLOG(1, OPENMONERO_LOG_CATEGORY)
                  ^~~~~
/home/monero/openmonero/src/TxSearch.cpp:297:9: note: in expansion of macro ‘OMVLOG1’
         OMVLOG1 << address_prefix + ": found some outputs in block "
         ^~~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note: candidate: ‘el::base::Writer::Writer(el::LogMessage*, el::base::DispatchAction)’
   Writer(LogMessage* msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) :
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note:   candidate expects 2 arguments, 6 provided
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note: candidate: ‘el::base::Writer::Writer(el::Level, el::Color, const char*, el::base::type::LineNumber, const char*, el::base::DispatchAction, el::base::type::VerboseLevel)’
   Writer(Level level, Color color, const char* file, base::type::LineNumber line,
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note:   no known conversion for argument 2 from ‘const char [41]’ to ‘el::Color’
/home/monero/openmonero/src/om_log.h:10:18: error: no matching function for call to ‘el::base::Writer::Writer(el::Level, const char [41], int, const char [43], el::base::DispatchAction, int)’
 #define OMVLOG1  CVLOG(1, OPENMONERO_LOG_CATEGORY)
                  ^~~~~
/home/monero/openmonero/src/TxSearch.cpp:470:9: note: in expansion of macro ‘OMVLOG1’
         OMVLOG1 << address_prefix + ": found some possible "
         ^~~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note: candidate: ‘el::base::Writer::Writer(el::LogMessage*, el::base::DispatchAction)’
   Writer(LogMessage* msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) :
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note:   candidate expects 2 arguments, 6 provided
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note: candidate: ‘el::base::Writer::Writer(el::Level, el::Color, const char*, el::base::type::LineNumber, const char*, el::base::DispatchAction, el::base::type::VerboseLevel)’
   Writer(Level level, Color color, const char* file, base::type::LineNumber line,
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note:   no known conversion for argument 2 from ‘const char [41]’ to ‘el::Color’
/home/monero/openmonero/src/TxSearch.cpp: In member function ‘virtual void xmreg::TxSearch::ping()’:
/home/monero/openmonero/src/om_log.h:11:18: error: no matching function for call to ‘el::base::Writer::Writer(el::Level, const char [41], int, const char [37], el::base::DispatchAction, int)’
 #define OMVLOG2  CVLOG(2, OPENMONERO_LOG_CATEGORY)
                  ^~~~~
/home/monero/openmonero/src/TxSearch.cpp:697:5: note: in expansion of macro ‘OMVLOG2’
     OMVLOG2 << address_prefix
     ^~~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note: candidate: ‘el::base::Writer::Writer(el::LogMessage*, el::base::DispatchAction)’
   Writer(LogMessage* msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) :
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note:   candidate expects 2 arguments, 6 provided
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note: candidate: ‘el::base::Writer::Writer(el::Level, el::Color, const char*, el::base::type::LineNumber, const char*, el::base::DispatchAction, el::base::type::VerboseLevel)’
   Writer(Level level, Color color, const char* file, base::type::LineNumber line,
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note:   no known conversion for argument 2 from ‘const char [41]’ to ‘el::Color’
/home/monero/openmonero/src/TxSearch.cpp: In member function ‘virtual bool xmreg::TxSearch::delete_existing_tx_if_exists(const string&)’:
/home/monero/openmonero/src/om_log.h:10:18: error: no matching function for call to ‘el::base::Writer::Writer(el::Level, const char [41], int, const char [74], el::base::DispatchAction, int)’
 #define OMVLOG1  CVLOG(1, OPENMONERO_LOG_CATEGORY)
                  ^~~~~
/home/monero/openmonero/src/TxSearch.cpp:978:9: note: in expansion of macro ‘OMVLOG1’
         OMVLOG1 << '\n' << address_prefix
         ^~~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note: candidate: ‘el::base::Writer::Writer(el::LogMessage*, el::base::DispatchAction)’
   Writer(LogMessage* msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) :
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3266:3: note:   candidate expects 2 arguments, 6 provided
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note: candidate: ‘el::base::Writer::Writer(el::Level, el::Color, const char*, el::base::type::LineNumber, const char*, el::base::DispatchAction, el::base::type::VerboseLevel)’
   Writer(Level level, Color color, const char* file, base::type::LineNumber line,
   ^~~~~~
/home/monero/monero/external/easylogging++/easylogging++.h:3259:3: note:   no known conversion for argument 2 from ‘const char [41]’ to ‘el::Color’
src/CMakeFiles/myxmr.dir/build.make:206: recipe for target 'src/CMakeFiles/myxmr.dir/TxSearch.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxmr.dir/TxSearch.cpp.o] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/CMakeFiles/myxmr.dir/all' failed
make[1]: *** [src/CMakeFiles/myxmr.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by moneroexamples** [comment]
You have to specify which monero and openmonero branches you are using. OM has not been yet adopted to compile with the current master branch of monero (i.e. the one with randomx upgrade).

Also check this: https://github.com/moneroexamples/openmonero/issues/166#issuecomment-553869063

**Comment by M-Adeel-Danish** [comment]
Thank you for your response. Current version is monero release-v0.15, openmonero master branch 507bda0. 

So, I have to downgrade monero release to v0.14.*?

**Comment by moneroexamples** [comment]
> So, I have to downgrade monero release to v0.14.*?

Yes, if you want to check OM right now. But with upcoming monero hf v0.14 will not be useful. I'll try to fix OM before the hf happens, so you can wait a bit if you want.

**Comment by M-Adeel-Danish** [comment]
Ok, sure I can wait. Can you kindly give me expected time for fix.

**Comment by moneroexamples** [comment]
Don't fixed  time frame, sorry. Hopefully by the end of November.

**Comment by paulshapiro** [comment]
@M-Adeel-Danish for what it's worth, we do make the mymonero API hosting available to third parties (it's the API that OM implements); if you're desperate to keep your service going through the hardfork, drop me a line at paul@mymonero.com

**Comment by M-Adeel-Danish** [comment]
> Don't have fixed time frame, sorry. Hopefully by the end of November.

Thank you team. That helps a lot.

**Comment by M-Adeel-Danish** [comment]
> @M-Adeel-Danish for what it's worth, we do make the mymonero API hosting available to third parties (it's the API that OM implements); if you're desperate to keep your service going through the hardfork, drop me a line at [paul@mymonero.com](mailto:paul@mymonero.com)

@paulshapiro thank you for the insight. I will be contacting you soon.
