### ISSUE TITLE
Change mixin to ring size

### ISSUE THREAD

**Issue by alvinjoelsantos** [moneroexamples/openmonero#22]
I have changed the terms in the following: https://github.com/alvinjoelsantos/openmonero/commit/c224202f084d5ebb3f41121d70b85ab69006ad99

**Issue**: unconfirmed transactions still show mixin, but once confirmed, correct ring size number is shown. I'm not sure where to modify unconfirmed mixin value. Testnet: http://ajs.hopto.org/openmonero

![064107](https://cloud.githubusercontent.com/assets/13996922/26273802/de0e093a-3d40-11e7-9a11-8097c773e653.png)

**Comment by moneroexamples** [comment]
Thanks. Unconfirmed txs, i.e., those in mempool, require special treatment. 

The mixin for them is set in these two lines:

https://github.com/moneroexamples/openmonero/blob/master/src/TxSearch.cpp#L550

https://github.com/moneroexamples/openmonero/blob/master/src/TxSearch.cpp#L643

**Comment by moneroexamples** [comment]
Hi. Its live on dev server now: http://139.162.32.245:81

Thanks again, and as always, if you have any comments or issues for open monero or the onion explorer, please feel free to let me know.
