### ISSUE TITLE
[feature] use integrated addresses

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/openmonero#26]
Add using integrated addresses for receiving coin and making import payments.

**Comment by JamesKegel** [comment]
I'd quite like this, thank you for your work

**Comment by moneroexamples** [comment]
Thanks. I also think it would be useful. I will look into it when I finish the time based import of txs and refactoring tx imports.

**Comment by moneroexamples** [comment]
Integrated address have been added and are live on testnet wallet (http://139.162.32.245:81/) if you want to have a look. There is default mnemonic set already, so you can grab some testnet xmr from it if you want.

Legacy address+payment_id in `Receive` window and in Importing transactions, have been replaced with integrated address. Time based import of recent txs also have been added, btw.
