### ISSUE TITLE
Error: Can't connect to the backend! Maybe its down.

### ISSUE THREAD

**Issue by JamesKegel** [moneroexamples/openmonero#27]
Ubuntu Server 16.04
Provider is Scaleway.com
box size is C2L, 8cpu32ram

steps to reproduce  
https://github.com/moneroexamples/openmonero/blob/master/README.md
chrome browser - exampleapp.com/

result is that the app successfully creates a mnemonic key, however there is a notification on the splash page that says `Error: Can't connect to the backend! Maybe its down.`

pasting the mnemonic key in the box below it after being created gives the following error: `server error`.

a clue, the title bar branding says "testnet" despite all testnet options set to false as well as openmonero being run without the testnet option.

**Comment by moneroexamples** [comment]
Backend is running normally? Can you see an output, for example:

```
Blockchain path: /home/mwo/.bitmonero/lmdb
Start the service at http://localhost:1984
Check block height: 1347798 no of mempool txs: 6
Check block height: 1347798 no of mempool txs: 7
Check block height: 1347798 no of mempool txs: 7
Check block height: 1347798 no of mempool txs: 7
```
My mainnet test version is running http://139.162.32.245:82/#/, so this is in my conifg.js (only relevant part shown)

```
  "frontend-url": "http://139.162.32.245:82",
  "daemon-url" :
  {
    "mainnet" : "http:://127.0.0.1:18081",
    "testnet" : "http:://127.0.0.1:28081"
  },
```

And this is relevant part from html/js/config.js
```
apiUrl: "http://139.162.32.245:1984/",
testnet: false,
``` 

Also, can check to see if chrome console shows any errors. 

Other thing is that chrome may cache things for long time. If you used chrome to access testnet, than changed to mainet, in chrome still can be serving testnet fronted from its cache. You can check using firefox or other browser, and if this is the case, force clear refresh of the chrome, without using its caching.

**Comment by JamesKegel** [comment]
Curiously, mine is missing  `"frontend-url": "http://139.162.32.245:82",`  entirely.

**Comment by JamesKegel** [comment]
I noticed, while looking at your test net that you have the same DB errors as I'm seeing. Are we experiencing the same thing or is your backend not currently running? The difference between both of our test servers, though, is that yours is on mainnet while mine is stuck on test net.

**Comment by moneroexamples** [comment]
Yes, my open monero for mainnet (i.e., http://139.162.32.245:82) is not running at the moment. Only testnet one is up http://139.162.32.245:81 for now, as most recent developments are being tested using testnet.
