### ISSUE TITLE
crash on startup (std::system_error) on pine64

### ISSUE THREAD

**Issue by Jaqueeee** [moneroexamples/openmonero#31]
Managed to get openmonero running on my pine64 yesterday. Today it's crashing on startup. Daemon (testnet) is running, fully synced. Any clues? 

```
$ ./openmonero -t
Blockchain path: /media/external/testnet/lmdb
2017-07-22 08:00:40.365	      7f991c4000	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
Check block height: 959259 no of mempool txs: 0
Start the service at http://localhost:1984
terminate called after throwing an instance of 'std::system_error'
terminate called recursively
Aborted
```

Full BT https://paste.fedoraproject.org/paste/fxZOx9rg3TuRJVqHiYpHJQ/raw

**Comment by moneroexamples** [comment]
Based on the last last line in the BT, i found this and arm cpus: https://stackoverflow.com/questions/32023492/backtrace-stopped-previous-frame-identical-to-this-frame-corrupt-stack-on

And in the post it seems as `libcurl` and ssl were causing the problem. Did you try using openmonero with `ssl` now, and before without?

**Comment by Jaqueeee** [comment]
I didn't change anything between the two runs except stopping monerod and restarted it. Weird. Thanks for the hint. Tried with SSL enabled now without success. I'll try to get gdb working with the linked libs.

**Comment by Jaqueeee** [comment]
no success. Switching to amd64 platform instead. closing.
