### ISSUE TITLE
wrong result from get_address_txs?

### ISSUE THREAD

**Issue by Jaqueeee** [moneroexamples/openmonero#33]
Since I can't get my own server running (#31) I'm using your testnet server (http://139.162.32.245:81) currently. Is it running master or something else? I'm suspecting that get_address_txs is giving me weird results. On #/transactions I'm only seeing incoming tx's. I can dig deeper into it if you don't already know what's causing it.

**Comment by moneroexamples** [comment]
test server is running `Open Monero version: upgrade_angularjs-2017-07-16-9ead4db` which is `upgrade_angular` branch: https://github.com/moneroexamples/openmonero/tree/upgrade_angularjs

The branch has numerous changes (time based imports, integrated address, upgraded angularjs, angular cleanups), mostly to frontend. However `get_address_txs` got new value returned  `scanned_block_timestamp`, but it should not affect anything. In old frontend it would be simply be not used.

**Comment by Jaqueeee** [comment]
I added this testnet wallet. 
`joyous ruined enhanced behind rally gadget audio cuddled omnibus useful puddle taunts rebel teardrop cottage zombie oven camp moment omega lettuce jockey tamper technical ruined `

On transactions tab all tx's show positive amounts, which is not correct. Example:
`9db3eba8105e234aad254d8fc7cf7b292c1ed077e06e2e85c8a20cba9953c40d` from March 5th is shown as an incoming TX of 24.500987836534 XMR. In Monero GUI it's an outgoing TX of 5 XMR + 0.03xxx fee. 

Another example is `94d9e73d72a92547f6a0c6a9bc967a663082b9ab1df7d6ad94c0561c36a3396c` from January 4th. It's a tx sent to myself. In Monero GUI it's shown as amount 0 and fee 0.03xxxx. In OpenMonero it's shown as a positive amount of 999.965323480993.

I also noted the default testnet wallet also shows positive amounts only.

**Comment by moneroexamples** [comment]
I see. It shows incoming txs only (i.e. change returned to you). But the overall wallet balance (i.e., 80.409981421942 XMR) should be ok? 

If balance is ok, this means that backend correctly fetches all txs to the frontend (thus balance is ok), just JavaScript incorrectly lists txs in the account overview and transaction list. I will look into it.

**Comment by Jaqueeee** [comment]
yes, balance is correct. It could be a js error. Though, i was suspecting that the wallet balance was calculated by the data from get_address_info and not get_address_txs in the web wallet?

I'm not seeing this error on mainnet when using myMonero backend, which makes me think it could be a backend error.

**Comment by moneroexamples** [comment]
You were right. It was backend problem. Was using wrong tx public key for spent outputs in get_address_txs. It has been fixed for txs both in blockchain and mempool. Should be ok now. 

`upgrade_angularjs` branch was updated to reflect this fix. The dev testnet version (http://139.162.32.245:81) was also updated. If you have more wallets on my dev testnet version, you need to use import transactions, as the fixed involved one change to mysql, and subsequently, rescanning of the blockchain is needed. Without rescan, wallet will not work. I already performed rescan for the wallet you gave as an example, but not for others, if you have any.

**Comment by Jaqueeee** [comment]
Thanks! Works great now.
