### ISSUE TITLE
Add api version to get_version call

### ISSUE THREAD

**Issue by Jaqueeee** [moneroexamples/openmonero#35]
Will be needed in future, when api gets updated. Ideally it should be aligned with mymonero api. 
@vtnerd

**Comment by moneroexamples** [comment]
I can add it rpc api version to current `get_version` call. A api version number similar to `CORE_RPC_VERSION` in monero would be good i think?

**Comment by Jaqueeee** [comment]
Yes. That's a great idea.

**Comment by moneroexamples** [comment]
I added tentatively the api version to upgrade_angularjs branch. It is already being displayed in the dev testnet version: http://139.162.32.245:81 . The versioning in the backend is based on `CORE_RPC_VERSION` stype, i.e., 

```c++
#define OPENMONERO_RPC_VERSION_MAJOR 1
#define OPENMONERO_RPC_VERSION_MINOR 0
#define MAKE_OPENMONERO_RPC_VERSION(major,minor) (((major)<<16)|(minor))
#define OPENMONERO_RPC_VERSION \
    MAKE_OPENMONERO_RPC_VERSION(OPENMONERO_RPC_VERSION_MAJOR, OPENMONERO_RPC_VERSION_MINOR)
```

**Comment by Jaqueeee** [comment]
Thanks!
