### ISSUE TITLE
implement new_address status in login request

### ISSUE THREAD

**Issue by Jaqueeee** [moneroexamples/openmonero#36]
It's hardcoded to always return false it seems. 
https://github.com/moneroexamples/openmonero/blob/master/src/YourMoneroRequests.cpp#L99

**Comment by moneroexamples** [comment]
It has no use in frontend in mymonero from what I can tell. I added it into open monero initially  just to return it, but I dont know what purpose it has, or had, in mymonero. Maybe it was used in some older versions of the frontend, and now its not used anymore, but still returned. open monero is also not using it. I can remove it if needed.

**Comment by Jaqueeee** [comment]
In mymonero backend it seems to indicate if the address is known or not. I was thinking it could be used by frontend to inform user who is recovering from seed/keys that they might need to pay the import fee. For fresh wallets it doesn't have any use.

**Comment by moneroexamples** [comment]
Openmonero does not differentiate between creating account with keys or mnemonic seed, as mnemonic seed in openmonero is fully compatible with normal monero seeds. 

But it makes sense to indicate to user that he is creating new account (i.e., new entry in mysql), regardless whether the user uses a seed or private keys, if not using "Create a new account" option in open monero.

Will look into this. Thanks.

**Comment by moneroexamples** [comment]
Should work now. New accounts, creating by using existing mnemonic seed or keys, are greeted with import window. But new accounts created using "Create a new account" dont have this. Can check on testnet: http://139.162.32.245:81/ and this can be used for creating  addresses for tests https://xmr.llcoins.net/

Also I added readline dependency.

**Comment by Jaqueeee** [comment]
perfect, thanks!
