### ISSUE TITLE
Ability to disable fees for personal use

### ISSUE THREAD

**Issue by unixfox** [moneroexamples/openmonero#43]
I'm running my own instance of openmonero and this instance is locked by a HTTP login.
If I want to import all my transactions I've to pay a fee but it's a bit stupid to pay a fee to yourself so is it possible to introduce a way to disable the fee requirement for importing all transactions?

**Comment by moneroexamples** [comment]
In `config/config.json` the fee is set to default 0.01 (i.e., 10000000000). I think setting it to 0, will not work in this case. Dont remember, have to check. This is obviously a bug if zero fee will require any tx. I will fix that if this is the case. 

In the meantime, you can manually change in mysql `Accounts`, the filed `scanned_block_height` to 0. Scanning should begin from scratch when you relogin or restart the back-end.

There are also time based imports, which are free by default. 

p.s. all current development is happening in this branch: https://github.com/moneroexamples/openmonero/tree/upgrade_angularjs 

So when I change the import all tx fee, in will be in that branch.

**Comment by unixfox** [comment]
I'm already on the dev branch and I tried the same thing as you setting the fee at 0 but that doesn't disable the fee.
I'll to bypass using MySQL.

**Comment by moneroexamples** [comment]
It will work soon. I already made changes in my locol branch, havent pushed them yet to git hub. Need to test few things. So probably today I will do that.

**Comment by moneroexamples** [comment]
Added free imports. If fee in `confin/confing.json` is 0, full importing of the wallet should work now without needed any fees.

**Comment by unixfox** [comment]
Works great, thank you.
