### ISSUE TITLE
Calculation error : the final balance is different from the monero-wallet-cli on mainnet

### ISSUE THREAD

**Issue by unixfox** [moneroexamples/openmonero#44]
Openmonero reports a different value of the final balance compared to monero-wallet-cli on mainnet.
According to openmonero I've 159XMR but the monero-wallet-cli and monero-wallet-gui reports that I've 5.25XMR.
I tried to reimport twice by erasing the MySQL database and I got two different value on the two trials.
Openmonero: ![](https://i.imgur.com/RF6gcVx.png)
Monero wallet cli: ![](https://i.imgur.com/p7cmpwh.png)
Monero wallet gui: ![](https://i.imgur.com/lZcJWUT.png)

**Comment by moneroexamples** [comment]
If you use master branch, it was bug.

https://github.com/moneroexamples/openmonero/issues/33

It was fixed. But all changes are in this branch:

https://github.com/moneroexamples/openmonero/tree/upgrade_angularjs

You can try running this branch. It requires monero development version from master as well. So you would need to recompile monero probably as well, if you are not running current development version.

If using this branch you still have wrong balance, then there must be some new bug tough.

**Comment by unixfox** [comment]
I don't use the master branch but I don't currently use the monero development version I'll try to switch to it tomorrow. I keep you informed.

**Comment by moneroexamples** [comment]
Thanks.
One more question. Do you see any negative values for tx in open monero for that wallet? If you see only positive values, then spendings are not accounted for, and what you see is basically a view only wallet. So this was the bug before. 

I think it is same issue, but I will check as well on mainnet wallet anyway. Most my development is done on testnet. So maybe there is some problem with mainnet wallets, which does not occur for testnet.

**Comment by moneroexamples** [comment]
And one more. Make sure that you have database setup using sql file from this branch as well: https://github.com/moneroexamples/openmonero/tree/upgrade_angularjs/sql

**Comment by unixfox** [comment]
I do use the SQL from the `upgrade_angularjs` branch because openmonero doesn't work with the SQL from the master branch. I'll see in a few hours if it's related to the fact that I used the stable version of monero.
I saw a couple of negative values for tx but some of them weren't the same amount as the values on `monero-wallet-cli`.

**Comment by moneroexamples** [comment]
Ok. If the problem persist, will continue discussion again. Btw, I check my mninnet wallets today, and they all worked well with open monero, so at least on my end difficult to see what is happening atm. Maybe later you can check if you can replicate issue with some testnet wallet? If it would be possible replicate on testnet, then you could just give me the testnet seed, and I can investigate on my end.

**Comment by unixfox** [comment]
Sorry for the waiting, synchronizing the blockchain takes a couple of days (even on a good computer).

It seems that running the development version of monero doesn't resolve the issue and now openmonero reports me an higher value than before: ![](https://i.imgur.com/dhzXvAb.png)

```
[monero@vps openmonero]# git status
On branch upgrade_angularjs
Your branch is up-to-date with 'origin/upgrade_angularjs'.
```
```
[monero@vps ~]$ /opt/monero/build/release/bin/monerod --version
Monero 'Helium Hydra' (v0.11.0.0-72b5f37f)
```

**Comment by moneroexamples** [comment]
When you open javascript console, do you see any errors? 

Also, by any chance, can you replicate the problem with a testnet wallet? In addition, could you provided a tx hash of a tx that is incorrectly shown in the open monero? Finally, did you check with any other mainet wallet? Is this a problem with all your wallets, or only this one in particular?

**Comment by unixfox** [comment]
I've no error in my javascript console.

I don't know how the testnet works, is it supposed to have the same blockchain as the mainnet? Because my wallet is empty if I open it on a openmonero instance running on testnet.

These negative tx have incorrect value on openmonero:
- `63941a9ca01f0e725821b91816868c85e6b711298d00c3720081ab1c690c2b5e`
- `510b54a36b27831e0d60a9f63cdcc487b9700fce7ad678b13a2151ffbe62b2ac`
- `6b3ac8e5e2cec36db0f3c659ea173950e465a87be233b69ebc6e1d1a08abebde`

I don't have any problem with my other wallet even with an older wallet.

**Comment by moneroexamples** [comment]
Thank you. I suspect it has something to do with key_images (i.e. your spendings). The backend makes guesses about your possible spendings, and then all guesses are sent to the front-end. Since fornt-end has the spendkey, it can filter-out incorrect guesses, thus the balance should be calculated.

The three txs you provided have lots of key_images. Maybe i dont save them all correctly. I will investigate this.

Meantime, testnet has its own blockchain, so you would need to run second node, for testnet, and have testnet wallets. But for now its ok. I will check the code how it behaves with many key images.

**Comment by moneroexamples** [comment]
I did one change, so that all key images are scanned. Maybe this will help, if you can check? The import will be longer now, though. Unfortunately I cant replicate this problem using mine testnet and mainet wallets, so basically at the moment it is a guessing game what could be the reason for this.

**Comment by unixfox** [comment]
Why did you push the fix on the master branch? I'm using the `upgrade_angularjs` branch but it's ok I manualy edited the file.

The final balance on openmonero is almost exactly the same as the final balance on `monero-wallet-cli`.
There is still one transaction that is different on openmonero: `cc58ce6754f26bf83615188c25860e84467ee8e33e7c70818a187ec4e69af997`

**Comment by moneroexamples** [comment]
I'm sorry, that was mistake by pushing to master. I pushed the change to `upgrade_angularjs` now. Did not notice  I was on the wrong branch. 

The wrong tx is spending txs as well? It has wrong negative value?

**Comment by unixfox** [comment]
It was a wrong negative value indeed. The difference between openmonero and monero-wallet-cli was 7XMR for this transaction.

**Comment by moneroexamples** [comment]
So all txs seem to be good now, except this one: cc58ce6754f26bf83615188c25860e84467ee8e33e7c70818a187ec4e69af997 ? And the difference is exactly 7.0 xmr, not for example, 7.4027...?

**Comment by unixfox** [comment]
I'm sorry I was on my phone that's why I didn't know the exact difference.
The difference between openmonero and `monero-wallet-cli` for the transaction `cc58ce6754f26bf83615188c25860e84467ee8e33e7c70818a187ec4e69af997` is exactly 7,560800675XMR.

**Comment by moneroexamples** [comment]
This amount is very similar to coinbase tx that miners receive. Do you solo mine? I ask because the tx in question uses several coinbase txs in their ring signatures. Maybe one of them is not recognised correctly by the backend.

**Comment by unixfox** [comment]
I mine only on a pool and I don't know if it's related to the transactions that my pool send me.

**Comment by moneroexamples** [comment]
The other wallets you checked  and they worked, also contain pool payouts txs?

**Comment by unixfox** [comment]
Yes I've other wallets that contains pool payouts txs.

**Comment by moneroexamples** [comment]
I'm wondering about this coinbase tx: https://moneroexplorer.com/tx/27fa98952d4c3fdeee636ecbf2b61abc3a77d3515786530396ffc7ca4ac4c872

Can you check if you have such tx in your monero wallet (correctly working, like cli wallet)?

**Comment by unixfox** [comment]
I don't really understand what you want me to check because I don't have much experience in the monero blockchain. Can you explain me in other/simple words?

**Comment by moneroexamples** [comment]
That's fine. I already looked more into that tx, and I think it was not what I had initially though. At the moment I dont know what could be the problem. Probably have to wait till someone else will have similar miscalculation of their balance or I will encounter similar problem with my wallets.

**Comment by unixfox** [comment]
I want to notify you that I've got a correct balance, since my last comment I reinstalled my VPS so I restarted from scratch.
Maybe it's related to the new version of monerod?

**Comment by moneroexamples** [comment]
Thanks for update. Difficult to say. But glad its working now. So I guess its ok to close the issue for now?

**Comment by unixfox** [comment]
Sure, if I come across again with this bug in the future I'll reopen it.
