### ISSUE TITLE
Cant spend outputs originating from sweap all command?

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/openmonero#53]
Double check if you can spend using open monero outputs that were obtained by executing `sweep all` command in simplewallet

**Comment by stoffu** [comment]
> outputs that were obtained by executing `sweep all` command in simplewallet

Do you mean those outputs sent from others using `sweep_all`?
Whether the funds were sent using `transfer` or `sweep_all` shouldn't make any difference.

**Comment by moneroexamples** [comment]
I swept all one simplewallet into open monero, and then was not able to spend these funds in open monero. So I need to double check this. I was getting tx verification error in the node, when submitting raw tx from open monero. It could also be some mess up with sub-addresses during this time. Not sure yet.

**Comment by moneroexamples** [comment]
Seems ok now.
