### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by bitkron** [moneroexamples/openmonero#58]
/root/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::Blockchain(cryptonote::tx_memory_pool&)':
blockchain.cpp:(.text+0x823a): undefined reference to `cryptonote::checkpoints::checkpoints()'

/root/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::handle_block_to_main_chain(cryptonote::block const&, crypto::hash const&, cryptonote::block_verification_context&)':
blockchain.cpp:(.text+0x1de18): undefined reference to `cryptonote::checkpoints::is_in_checkpoint_zone(unsigned long) const'
blockchain.cpp:(.text+0x1de36): undefined reference to `cryptonote::checkpoints::check_block(unsigned long, crypto::hash const&) const'

/root/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::check_against_checkpoints(cryptonote::checkpoints const&, bool)':
blockchain.cpp:(.text+0x210c9): undefined reference to `cryptonote::checkpoints::get_points() const'
blockchain.cpp:(.text+0x21175): undefined reference to `cryptonote::checkpoints::check_block(unsigned long, crypto::hash const&) const'

/root/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::update_checkpoints(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
blockchain.cpp:(.text+0x21503): undefined reference to `cryptonote::checkpoints::load_checkpoints_from_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
blockchain.cpp:(.text+0x2158a): undefined reference to `cryptonote::checkpoints::checkpoints()'
blockchain.cpp:(.text+0x21594): undefined reference to `cryptonote::checkpoints::load_checkpoints_from_dns(bool)'
blockchain.cpp:(.text+0x2159f): undefined reference to `cryptonote::checkpoints::check_for_conflicts(cryptonote::checkpoints const&) const'
blockchain.cpp:(.text+0x216a3): undefined reference to `cryptonote::checkpoints::load_checkpoints_from_dns(bool)'

/root/monero/build/release/src/cryptonote_core/libcryptonote_core.a(blockchain.cpp.o): In function `cryptonote::Blockchain::handle_alternative_block(cryptonote::block const&, crypto::hash const&, cryptonote::block_verification_context&)':
blockchain.cpp:(.text+0x22660): undefined reference to `cryptonote::checkpoints::is_alternative_block_allowed(unsigned long, unsigned long) const'
blockchain.cpp:(.text+0x23362): undefined reference to `cryptonote::checkpoints::check_block(unsigned long, crypto::hash const&, bool&) const'
collect2: error: ld returned 1 exit status

**Comment by bitkron** [comment]
process stuck after 100% linking CXX. Please advice this issue. Thanks

**Comment by stoffu** [comment]
You need to build the v0.11.0.0 tag of Monero, as instructed in README. The checkpoint library was added to Monero after that tag.

**Comment by moneroexamples** [comment]
as @stoffu said.
Alternatively, if you use latest monero master version, you can use openmonero from this branch:
https://github.com/moneroexamples/openmonero/tree/compile_with_current_monero

**Comment by bitkron** [comment]
Thanks alot. its works now
