### ISSUE TITLE
Does not generate bulletproof txs.

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/openmonero#59]
Just like with introduction of RingCT, MyMonero/OpenMonero frontend fails to generate proper tx (i.e., bulletproof). So testnet v7 does not accept it.

**Comment by moneroexamples** [comment]
I checked, and still v7 accept plain old ringct txs for now. But sooner or later, will need to move on to bulletproofs.

**Comment by sebseb7** [comment]
you ready for v8?

**Comment by moneroexamples** [comment]
There is no bulletproof yet. Have to wait till MyMonero adds them. Once this happens I will add them to openmonero.

**Comment by moneroexamples** [comment]
Initial support for testing added in https://github.com/moneroexamples/openmonero/tree/mymonero_v9

**Comment by moneroexamples** [comment]
Done using mymonero-core-js.
