### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by bitkron-project** [moneroexamples/openmonero#61]
I've manage to deploy locally. but I have problem putting it online. Getting HTTP ERROR 501. I suspect the Lighttpd config. By the way I'm deploying on Ubuntu 16 server.

**Comment by moneroexamples** [comment]
You can also use appach, or ngnix for http server, if that would be easier to setup.

**Comment by bitkron-project** [comment]
thanks, manage to deploy with nginx
