### ISSUE TITLE
Incorrect values of funds (times 10)

### ISSUE THREAD

**Issue by propercoil** [moneroexamples/openmonero#62]
The values that are showing up in the balance is 10x the correct amount.
I'm on the `origin/sending_to_subaddress` branch with latest monero.

The only thing that I can think about was that during the installation there were "narrowing" warnings from long long int to something smaller.

**Comment by moneroexamples** [comment]
Does it mean that all tx that are being listed are also 10x larger? Or maybe one tx is wrong which results in wrong balance? Or just the balance displayed is incorrect, but tx are ok?

**Comment by propercoil** [comment]
Seems as though all tx's are 10x. Maybe it's an issue with the 32bit machine. I'm testing now on 64 and will update.

**Comment by moneroexamples** [comment]
Ok, thanks. I've never tested on 32bits, would be good to know if this causes some issue.

**Comment by moneroexamples** [comment]
Any update on this issue?

**Comment by moneroexamples** [comment]
Closing due to lack of updates
