### ISSUE TITLE
What is crypto.js for?

### ISSUE THREAD

**Issue by evanrolfe** [moneroexamples/openmonero#67]
There is a minified js file [crypto.js](https://github.com/moneroexamples/openmonero/blob/master/html/js/crypto.js), what is this for and why is it minified?

Running it through a js formatter gives us a a file which is ~17,000 lines long (see gist link below). Why is all of this code necessary? Looking at the code there are a lot of functions which I don't see having anything to do with monero i.e. `function fullScreenChange()`
https://gist.github.com/evanrolfe/5e7951975b3707835f764e642e952de4#file-crypto-js-L4720

Maybe I'm missing something but if openmonero / mymonero are open source applications which run in your browser, doesn't having a minified file like crypto.js make it harder for users to verify the source code doesn't contain anything malicious?

**Comment by moneroexamples** [comment]
The crypto.js in openmonero (like most frontend files) was taken directly from mymonero:
https://mymonero.com/js/crypto.js . This file is also used on xmr tests (https://xmr.llcoins.net/js/crypto.js). The minified code of crypto.js is also part of future mymonero mobile app(https://github.com/mymonero/mymonero-core-js/blob/master/cryptonote_utils/cryptonote_crypto_EMSCRIPTEN.js).

Unfortunately, I don't have un-minified version. The file is dependency for cn_utils.js. It provides functions such as `_malloc` or `ccall` `_free` used in cn_utils.js. I think crypto.js is a generic cryptographic library (don't know its origin), so its possible that some functions in it are not used in mymonero, xmr tests and openmonero. 

I tried looking for its origin, but without luck. If you know the original project that developed crypto.js, I can update it in openmonero, or add some info to crypto.js file where it comes from, as for example it is written in jquery.min.js.

**Comment by evanrolfe** [comment]
@moneroexamples Thanks for the reply! Ok I will raise this issue in the mymonero repo and update this issue if I find any more information.

**Comment by moneroexamples** [comment]
Closing as it is explained in the linked isssue.
