### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Zelwood3** [moneroexamples/openmonero#68]
I am getting this error when submitting request for new wallet address "{"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://127.0.0.1:1984/login","data":{"withCredentials":true,"address":"42SQdYY6X9qB1JgCJB2jgDgWAeisPcVqxAPpab7HkpxFXGXoqRxRGdvHf62cCZVZ2vjotQGZbP9HR3n2xgSMyy9VFeTNdAL","view_key":"df4668f9f8a1ce480ee0d9e3926b6bf1756133f81315fbdb068ac46e0f632000","create_account":true},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"withCredentials":false},"statusText":""}"

**Comment by moneroexamples** [comment]
Did you run and specify backends url in html/js/config.js, e.g., `apiUrl: "http://127.0.0.1:1984/",` and set `  testnet: true,` to true or false, depending if you running testnet node or mainnet one?

**Comment by Zelwood3** [comment]
Im founder of project I'll run it by my Developer tomorrow.

**Comment by Zelwood3** [comment]
Hello I reached out to me

**Comment by Zelwood3** [comment]
Hello have you reached out to khs125 on this issue we are having issues getting the word sentence verified and opening a new wallet. Please keep me and him posted to correct the issue.

**Comment by Zelwood3** [comment]
P.s. he is the person who uploaded the code to my clean SL8 file under wallet using your code

**Comment by moneroexamples** [comment]
Do you have any errors regarding "word sentence verified"? Maybe something in js console shows up, or the backend prints something?

**Comment by Zelwood3** [comment]
NVM apparently it is now fixed lol set to waste your time guess you guys
communicate the issue

**Comment by moneroexamples** [comment]
Issue seems fixed.
