### ISSUE TITLE
Faild created a search thread when login

### ISSUE THREAD

**Issue by SergeyAnkarenko** [moneroexamples/openmonero#72]
Hi!
Ubuntu 16.04

When trying to login using 
```curl  -w "\n" -X POST http://127.0.0.1:1984/login -d '{"address": "A2VTvE8bC9APsWFn3mQzgW8Xfcy2SP2CRUArD6ZtthNaWDuuvyhtBcZ8WDuYMRt1HhcnNQvpXVUavEiZ9waTbyBhP6RM8TV", "view_key": "041a241325326f9d86519b714a9b7f78b29111551757eeb6334d39c21f8b7400"}'```

Get this error.  
```
osboxes@osboxes:~/openmonero/build$ sudo ./openmonero
Blockchain path: /home/osboxes/.bitmonero/lmdb
Start the service at http://127.0.0.1:1984
Check block height: 175586 no of mempool txs: 0
Check block height: 175686 no of mempool txs: 0
Error getting address: A2qMy9i5Dgt1dFzb6kB9rsffDEUisW69HWTRuEM8LiB13YKzFeR4YrFVxsA9cZeEF9F1hgGWb5JT7UAEhHKwKR1LJ13aYTT
Cant parse string address: A2qMy9i5Dgt1dFzb6kB9rsffDEUisW69HWTRuEM8LiB13YKzFeR4YrFVxsA9cZeEF9F1hgGWb5JT7UAEhHKwKR1LJ13aYTT
Faild created a search thread 
Check block height: 175786 no of mempool txs: 0
```

By the way, get_random_outs, get version api works fine

**Comment by moneroexamples** [comment]
When you login using web interface to that address it  works? Also do you use master branch of the open monero or development one?

**Comment by SergeyAnkarenko** [comment]
It doesn't work, when using web interface. I'm using master branch.

I've recieved this mnemonic using web interface
```woes vampire sack jewels joyous twice elapse altitude android cynical observant anecdote layout syllabus myth noodles uncle egotistic acoustic archer fawns molten together giving fawns```

When repeating private login key and trying to create new account, get this error
```
Faild created a search thread 
Error getting address: A2R8hNctDkVYuSD5XB4Gkr3VzivbvfHnYWyTLu3YJv9phUfSnxiUd6U6KgP8D42QMibLXoWWH4jYgVpEz47XsL37V5fqJVG
Cant parse string address: A2R8hNctDkVYuSD5XB4Gkr3VzivbvfHnYWyTLu3YJv9phUfSnxiUd6U6KgP8D42QMibLXoWWH4jYgVpEz47XsL37V5fqJVG
Faild created a search thread
```

By the way, when I derive view key and address from this mnemonic using https://xmr.llcoins.net/
I get different address ...
```
address:4AsbD7xcwPPYuSD5XB4Gkr3VzivbvfHnYWyTLu3YJv9phUfSnxiUd6U6KgP8D42QMibLXoWWH4jYgVpEz47XsL37V3i1Hy9
private view key:2c33e7e0d3bae1425a10acb52b2c7a2345de62171a3be05ad811af6ec0415b05
```
And eventually, when I try to login using new derived address and public key like 
```
curl  -w "\n" -X POST http://127.0.0.1:1984/login -d '{"address": 
"4AsbD7xcwPPYuSD5XB4Gkr3VzivbvfHnYWyTLu3YJv9phUfSnxiUd6U6KgP8D42QMibLXoWWH4jYgVpEz47XsL37V3i1Hy9", "view_key": "2c33e7e0d3bae1425a10acb52b2c7a2345de62171a3be05ad811af6ec0415b05"}'
```
I get success response 
```
{"new_address":true,"status":"success"}
```

**Comment by moneroexamples** [comment]
https://xmr.llcoins.net/ gives different address and viewkey because you are generating it for mainnet, and you have setup open monero for testnet. All monero networks (testnet, stagenet, and mainent) have different addresses.

Since you are using frontend in testnet (based on your address generated) do you also run  backend in testnet?

**Comment by SergeyAnkarenko** [comment]
Yes, that was the case, thank you very much!
