### ISSUE TITLE
Error: Can't connect to the backend! Maybe it is down. 

### ISSUE THREAD

**Issue by shineslyd** [moneroexamples/openmonero#73]
Hi,

I am trying to host openmonero locally. I am able to get openmonero talk to deamon. And I can use command line curl to interact with openmonero api calls. However, the website front-end does not get connected with the backend. 

I've followed all the instructions, still don't understand where the problem is.

Thank you!

**Comment by moneroexamples** [comment]
Are you getting any errors in frontend javascript console or backend's?

**Comment by shineslyd** [comment]
In chrome browser console:
Failed to load resource: 
127.0.0.1:1984/get_version 
net::ERR_CONNECTION_REFUSED

On backend, it is syncing with blockchain with no problem. I'm syncing on mainnet.

**Comment by moneroexamples** [comment]
If backend is set to mainnet, did you set front-end to mainnet as well (check testnet option in html/js/config.js )? Also I would recommend testing it out on testnet (hopefully soon will it also work with stagenet), as open monero is very much in development, so bugs possible.

**Comment by shineslyd** [comment]
I was using a VPS which is exposed to the internet. When I use my own computer, the problem is gone. I still don't know why using VPS will have this error. But anyway, you can close this issue now.

**Comment by moneroexamples** [comment]
If the backend is on the some VPS, you need to vpn's ip (url) address in `html/js/config.js`. Also make sure that firewall does not block the ports for the backend. 

I will close as you suggest. Please feel free to reopen if needed.
