### ISSUE TITLE
fatal error: release/version/version.h: No such file or directory

### ISSUE THREAD

**Issue by gg2001** [moneroexamples/openmonero#78]
`Scanning dependencies of target restbed
[  2%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o
[  5%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/rule.cpp.o
[  8%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o
[ 10%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o
[ 13%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o
[ 16%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/service.cpp.o
[ 18%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/session.cpp.o
[ 21%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/resource.cpp.o
[ 24%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/response.cpp.o
[ 27%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/settings.cpp.o
[ 29%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket.cpp.o
[ 32%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/ssl_settings.cpp.o
[ 35%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/session_manager.cpp.o
[ 37%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/http_impl.cpp.o
[ 40%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket_message.cpp.o
[ 43%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/socket_impl.cpp.o
[ 45%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/service_impl.cpp.o
[ 48%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/session_impl.cpp.o
[ 51%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_impl.cpp.o
[ 54%] Building CXX object ext/restbed/CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_manager_impl.cpp.o
[ 56%] Linking CXX static library librestbed.a
[ 56%] Built target restbed
Scanning dependencies of target myxrm
[ 59%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
In file included from /home/ubuntu/openmonero/src/MicroCore.h:11:0,
                 from /home/ubuntu/openmonero/src/MicroCore.cpp:5:
/home/ubuntu/openmonero/src/monero_headers.h:19:37: fatal error: release/version/version.h: No such file or directory
compilation terminated.
src/CMakeFiles/myxrm.dir/build.make:62: recipe for target 'src/CMakeFiles/myxrm.dir/MicroCore.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxrm.dir/MicroCore.cpp.o] Error 1
CMakeFiles/Makefile2:124: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

I am attempting to run this on Ubuntu, however I am running into an issue when i enter the make command for openmonero.

**Comment by moneroexamples** [comment]
use this branch

-  https://github.com/moneroexamples/openmonero/tree/sending_to_subaddress

Its not yet merged with master.
