### ISSUE TITLE
Using html and js files for a project?

### ISSUE THREAD

**Issue by gg2001** [moneroexamples/openmonero#79]
Hi, I would like to use some of the js and html files in an application I am working on. How would I license the application and credit this repository for providing the initial html and js?

**Comment by moneroexamples** [comment]
The html and js are mostly taken from mymonero. So all credit should go there. If you check js files in openmonero (e.g. https://github.com/moneroexamples/openmonero/blob/master/html/js/cn_util.js) they contain their orginal copyright notice.

**Comment by gg2001** [comment]
Ok, thank you.
