### ISSUE TITLE
Linking errors again

### ISSUE THREAD

**Issue by Monerocc** [moneroexamples/openmonero#80]
When I finished have some error :
`[100%] Linking CXX executable openmonero
/usr/bin/ld: cannot find -lcryptoxmr
collect2: error: ld returned 1 exit status
CMakeFiles/openmonero.dir/build.make:128: recipe for target 'openmonero' failed
make[2]: *** [openmonero] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/openmonero.dir/all' failed
make[1]: *** [CMakeFiles/openmonero.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

After checking, the final discovery is to see the git clone in your readme
`git clone --recursive https://github.com/monero-project/monero`

The --recursive parameter should not be added here. When I do this, it will compile successfully.
`git clone https://github.com/monero-project/monero`

**Comment by moneroexamples** [comment]
Thanks for info. Which OS by the way you use? Also do you use current monero master branch, or official release v0.12.0.0 (by checking out tag `git checkout -b last_release v0.12.0.0)`? 

`--recursive` parameter is there as monero instruction says to use it: https://github.com/monero-project/monero#cloning-the-repository 

I'm checking now if it build for me with and without `--recursive` parameter. Maybe its not needed after all.

**Comment by Monerocc** [comment]
Hi, I'm use Ubuntu 16.04 x64 and use official release v0.12.0.0 (by checking out tag git checkout -b last_release v0.12.0.0).
so just use no --recursive will be right.

I have another question. How to improve the synchronization speed of the web wallet? What I know is the content of the lmdb directly read by openmonero, so how to increase the efficiency?

**Comment by Monerocc** [comment]
Thank you for a answer.
