### ISSUE TITLE
Mistakes are made with the Monroe branch.

### ISSUE THREAD

**Issue by Monerocc** [moneroexamples/openmonero#81]
Hello
  I recently used a Monroe branch, [monerov,](https://github.com/monerov/monerov) whose fork height is 1564965 and wants to support it with openmonero, but now there is a problem.

 When I build compile and run it is normal, but it does not show the transaction after the block 1564965, because I read the database, after 1564965, the block balance is 0, what is the problem?

**Comment by moneroexamples** [comment]
Sorry, i don't know much about monerov. Openmonero was designed for monero.
