### ISSUE TITLE
Amount formatting

### ISSUE THREAD

**Issue by KyriakosPatsias** [moneroexamples/openmonero#90]
Hello, thank you for making this work free/open source.

I noticed that the amounts are not formatted as expected. For example, when I call the /get_address_info endpoint, it prints the total_received as:

"total_received": 10000000000000

The actual amount I have in that wallet is 10. I am assuming what is printed is the decimal representation of the amount, with 12 decimal points, and without the decimal point char. 
Is there a way to print the amount as a JSON number format, as a floating point, ie 10.000000000000?

**Comment by moneroexamples** [comment]
Dividing by `1e12` should help.

**Comment by KyriakosPatsias** [comment]
Yes, it does help. I figured as much, but wanted to verify. Thanks! 
The specific issue I was having was when serializing the amount, it is interpreted as an integer and because it is such a big number, it was giving me issues. But I found a way around it by deserializing the amount as string and then parsing it into a decimal.
