### ISSUE TITLE
Fees calculation differs between monero-wallet-cli and openmonero

### ISSUE THREAD

**Issue by hippich** [moneroexamples/openmonero#91]
Hi. I am observing different fees generated by monero-wallet-cli and openmonero when sending money.

From my understanding fee estimation uses same code from monero. So was wondering why difference might be showing up? 

I am setting ring size to 7 and priority to low.

**Comment by hippich** [comment]
Reading other issues... Is this due openmonero use of RingCT vs wallet-cli using bulletproofs?

**Comment by moneroexamples** [comment]
Frontend of openmonero uses code largely taken from  mymonero.com. Thus the fees are calculated by the js code from mymonero (e.g., https://mymonero.com/js/controllers/send_coins.js). Although slight modifications were done to js files in openmonero to add new features (e.g., tx priority selection, displaying private tx key) the general algorithms are same. 

> RingCT vs wallet-cli using bulletproofs

Openmonero does not use bulletproofs, nor mymonero.com. So once mymonero.com gets updated with bulletproof code, openmonero will follow.

**Comment by hippich** [comment]
thanks!
